### ISSUE TITLE
Fixed column?

### ISSUE THREAD

**Issue by cranesandcaff** [esvit/ng-table#112]
I'm currently using ng-table to create an order system for a subscription based software. I want customers to be able to move and reorder the table without changing the month. Basically a fixed column of months while the rest of the tables are moveable. Is there any way currently to do this? If not do you have plans to add it?

**Comment by dearlordlt** [comment]
+1

**Comment by gui66497** [comment]
+1

**Comment by Cuilz** [comment]
+1
