### ISSUE TITLE
Grouping & paging

### ISSUE THREAD

**Issue by karolbe** [esvit/ng-table#114]
When grouping is enabled together with paging grouping does not process all items in the data-grid but rather only items from a single page. This should not work like this in my opinion, groups should be created from all available data.

**Comment by mlabieniec** [comment]
:+1:  facing the same issue here, ideally it would be great to have the groups paginate (similar to the subtotal concept) rather than the entire table.

**Comment by fsm3xpert** [comment]
Review this issue #893
