### ISSUE TITLE
Wait timeouts

### ISSUE THREAD

**Issue by maklemenz** [esvit/ng-table#119]
Is it possible to not instantly search but throttle or debounce the data loading?
I want my users to have livesearch, but I don't want a request for every keystroke. I want my users to start typing filters and if the user stops typing for 300 ms I want to start the serversrequest.

It is possible since you can allways do what ever you like in your getData method, but I think this could be a feature ngTable could bring for itself.

**Comment by llamerr** [comment]
Is it possible also to duplicate that change into `ng-model-options="{debounce: filterDelay` somehow? Since from what I see it works different from debounce.
When I replaced template code like this

    $templateCache.put('ng-table/filters/text.html', '<input type="text" name="{{name}}" ng-disabled="$filterRow.disabled" ng-model="params.filter()[name]" class="input-filter form-control" placeholder="{{getFilterPlaceholderValue(filter, name)}}" ng-model-options="{debounce: 750}" /> ');

it started working like I wanted

**Comment by maklemenz** [comment]
@llamerr thank you for that input. Just for your information, if I remember correctly ng-model-options didn't exist back then.
