### ISSUE TITLE
multiple greater than / lower than / equals filters outside the table

### ISSUE THREAD

**Issue by fxck** [esvit/ng-table#123]
Looking at the examples I'm not quite sure how those filters work, are there any exposed functions you could use if you wanted to, say, make a filter where you 1) select a column in a selectbox, select a sign from a selectbox(>, <, = etc.), and then input a value. And posibility to do it for multiple columns at once.

Something like this kinda
![search](https://f.cloud.github.com/assets/1303561/1655749/dd1ef746-5b67-11e3-94c3-50a446e8d0e2.PNG)

**Comment by kamarali** [comment]
need to write custom directive
