### ISSUE TITLE
Search / Filter Multiple Columns from one Search Box

### ISSUE THREAD

**Issue by ghost** [esvit/ng-table#139]
Hello! Thanks for the plugin. 

I need to add a single search input above the entire table that will allow filtering of multiple columns. 

For example say I have a table of users. Columns name, email, phone and address. When I type "abc" into the filter box I would like to filter users who have "abc" anywhere in their name, email, phone or address.

Is this possible?

Thanks in advance.

**Comment by Ravik5** [comment]
Superb it works thanks buddy!!

**Comment by makkesk8** [comment]
Heres a better one:

originalData should be the data you started with.

```
$scope.$watch("searchData", function (value) {
    if(value !== '') {
      data = filterFilter(data, value);
      $scope.tableParams.total(data.length);
      $scope.tableParams.reload();
    }else{
      data = originalData;
      $scope.tableParams.total(data.length);
      $scope.tableParams.reload();
    }
  });
```
