### ISSUE TITLE
Should ng-table.map be requested at runtime?

### ISSUE THREAD

**Issue by aruizca** [esvit/ng-table#141]
First of all thank you for this beautiful component :-)

When debugging my app I can see that is asking for the ng-table.map file but I think that is not necessary.

Cheers,
Angel.

**Comment by joshblum** [comment]
@esvit why is the sourcemap included in the minified versions though? doesn't that eliminate any performance gains from minifying?

**Comment by christianacca** [comment]
See my comment: https://github.com/esvit/ng-table/issues/930
