### ISSUE TITLE
Sorting on multiple values

### ISSUE THREAD

**Issue by demands** [esvit/ng-table#160]
First I just want to say I absolutely love this project. It's so convenient. Thanks for all the awesome work!

Here's a question. I'm trying to sort a column that's based on multiple values. Here's an example, where I want to be able to sort by two dates with one click:

```javascript
var data = [
  { name: 'lincoln',    birth: 1809, death: 1865 },
  { name: 'fdr',        birth: 1882, death: 1945 },
  { name: 'washington', birth: 1732, death: 1799 },
  { name: 'jfk',        birth: 1917, death: 1963 },
  { name: 'darwin',     birth: 1809, death: 1882 },
  { name: 'poe',        birth: 1809, death: 1849 }
];

$scope.table = new ngTableParams({sorting: {name: 'asc'}}, {
  total: data.length,
  getData: function($defer, params) {
    $defer.resolve($filter('orderBy')(data, params.orderBy()));
}});
```

```html
<table ng-table='table'>
  <tr ng-repeat='row in $data'>
    <td data-title='Name' sortable="'name'">{{row.name}}</td>
    <td data-title='Lifespan' sortable="['birth', 'death']">{{row.birth}} - {{row.death}}</td>
  </tr>
</table>
```

`sortable="['birth', 'death']"` doesn't actually work in this case. I could just set sortable to `'birth'`, but then individuals born on the same day would be in an indeterminate order. Is there some way of achieving this that I am missing? Is it something that I could open a pull request for?

Thanks!
~Max

**Comment by furyscript** [comment]
Please +1
