### ISSUE TITLE
Dynamic Table filling and pagination problems

### ISSUE THREAD

**Issue by fyelci** [esvit/ng-table#163]
Hi,

I want to build a fully dynamic table with ng-table. It's columns and data will change on the fly. I have spent many hours with ng-table, but i think there is a bug on it.

When you want to change table's columns and data, you can change columns but not data. I have demo below, which I forked from your dynamic table sample.
http://plnkr.co/edit/KnUVGa

And one more problem, If  I can fill table with some workarounds, pagination doesn't work too.

**Comment by omkartelee** [comment]
thank you....it solved my problem also

**Comment by awii5** [comment]
Dear fyelci,

when im trying your example i am getting below screen. Please help me to get it run.

Thanks.

![image](https://cloud.githubusercontent.com/assets/20037694/17849357/070e6df2-6876-11e6-9a82-e278d6889fde.png)
