### ISSUE TITLE
sorting and dynamic data

### ISSUE THREAD

**Issue by hisraeli** [esvit/ng-table#177]
hi,
thanks for your help.

my problem is when i'm using sorting every thing works well in the first time.
but when i want to load new data to the table the data not changed.
the line getData (in tableParams) never readed again.
so the $data didn't updated and remain with the old data.

best regards,
Hillel.

**Comment by cboden** [comment]
Was this fixed or is the $watch still needed?

**Comment by iyel** [comment]
You need explicitly run tablePrarams.reload()
If you have suggestions - lets discuss

**Comment by cboden** [comment]
Thanks @iyel!
