### ISSUE TITLE
Pagination on top and bottom

### ISSUE THREAD

**Issue by gruskada** [esvit/ng-table#182]
I can't figure out how to get a pagination template to show up on the top and bottom of the table. In the source, if I try this:

return element.before(paginationTemplate).after("test");

the pagination template shows up before the table, and "test" shows up after, as expected.

But if I try this:

return element.before(paginationTemplate).after(paginationTemplate);

it only shows up after the table.

In any case, ideally there would be an attribute like pagination-location="top|bottom|topAndBottom" or something to that effect.

In the meantime, any ideas how to get this working by modifying the source?

**Comment by FrogDevelopper** [comment]
Hi !

is this issue resolved ? Cause I use the version 1.0.0-beta.7, and there is no way to position the pagination on the top other than modify the directive code :
`$element.after(paginationTemplate);` => `$element.before(paginationTemplate);` on the `compileDirectiveTemplates` function.

**Comment by justinr1234** [comment]
@esvit What is the proper solution to display a pagination control at the top? You didn't merge https://github.com/esvit/ng-table/pull/184 and is referring to an out of date link to demo 28

**Comment by robmosca** [comment]
I am also interested in how to easily and properly move the pagination controls to the top... any hint?

**Comment by BrianLian** [comment]
@robmosca @justinr1234 @FrogDevelopper 
Hi, all

about demo28 can see the commit https://github.com/esvit/ng-table/blob/83c572f536b0e6120385d69690f1c4c0204346ce/examples/demo28.html

the code like the following
```jade
div(ng-table-pagination="table.tp" template-url="'ng-table/pager.html'")
  table.table.table-condensed.table-bordered.table-striped.logtable(ng-table="table.tp" pagination-top show-filter="false")
    tr(ng-repeat="row in $data")
      td ...
```

**Comment by dsabhrawal** [comment]
I achieved this by playing with the template present in ngtable js file.
$templateCache.put('ng-table/header.html',      --- Responsible for header part.
$templateCache.put('ng-table/pager.html',        --- Available for footer part.

Change the tags according to your requirement.

**Comment by bradwbradw** [comment]
i know it's 2 years later, but if anyone finds this hack useful, expanding on above comment:

```
angular.module('yourModule').run(function($templateCache){
  let header = 'ng-table/header.html';
  let pager = 'ng-table/pager.html';
  let headerHtml = $templateCache.get(header);
  let pagerHtml = $templateCache.get(pager);

  $templateCache.put(header, pagerHtml + headerHtml);
  $templateCache.put(pager, "");
});
```

otherwise, I'd be interested in a config-based way of achieving this, but not sure it exists
