### ISSUE TITLE
tableParams.reload() Doesn't reset Page

### ISSUE THREAD

**Issue by agponte** [esvit/ng-table#187]
When data is refreshed I call tableParams.reload(), which does reload the data; however, it does not reset the paging.

For example, if I am on Page 5 of the data set then refresh the data which doesn't have a page 5, I remain on page 5 with an empty table.  Afterwards ngTable allows me to page forward to pages beyond what the new data set contains.

**Comment by tucq88** [comment]
Update for @nimeshvaghasiya 's answer (version 0.8.3): `$scope.tableParams.page(1)`
