### ISSUE TITLE
filter not working with dynamic columns

### ISSUE THREAD

**Issue by ankitjain2806** [esvit/ng-table#189]
Tried adding filter to the code present in the demos/example20

but i am not able to get the text boxes for the filters:

this is the html code : 
<html>
  <body ng-app="main" ng-controller="DemoCtrl">

    <table ng-table="tableParams" show-filter="true" class="table">
        <thead>
        <tr>
            <th ng-repeat="column in columns" ng-show="column.visible"
                class="text-center sortable" ng-class="{
                    'sort-asc': tableParams.isSortBy(column.field, 'asc'),
                    'sort-desc': tableParams.isSortBy(column.field, 'desc')
                  }"
                ng-click="tableParams.sorting(column.field, tableParams.isSortBy(column.field, 'asc') ? 'desc' : 'asc')">
                {{column.title}}
            </th>
        </tr>
        </thead>
        <tbody>
        <tr ng-repeat="user in $data">
            <td ng-repeat="column in columns" ng-show="column.visible" sortable="column.field" title = "{{column.title}}"  filter = "column.filter" >
                {{user[column.field]}}
            </td>
        </tr>
        </tbody>
    </table>
  </body>
</html>

this is the js code : 
<code>
var app = angular.module('main', ['ngTable']).
        controller('DemoCtrl', function($scope, $filter, ngTableParams) {
            var data = [{name: "Moroni", age: 50},
                {name: "Tiancum", age: 43},
                {name: "Jacob", age: 27},
                {name: "Nephi", age: 29},
                {name: "Enos", age: 34},
                {name: "Tiancum", age: 43},
                {name: "Jacob", age: 27},
                {name: "Nephi", age: 29},
                {name: "Enos", age: 34},
                {name: "Tiancum", age: 43},
                {name: "Jacob", age: 27},
                {name: "Nephi", age: 29},
                {name: "Enos", age: 34},
                {name: "Tiancum", age: 43},
                {name: "Jacob", age: 27},
                {name: "Nephi", age: 29},
                {name: "Enos", age: 34}];
            $scope.columns = [
                { title: 'Name', field: 'name', visible: true, filter: { 'name': 'text' } },
                { title: 'Age', field: 'age', visible: true }
            ];
            $scope.tableParams = new ngTableParams({
                page: 1,            // show first page
                count: 10,          // count per page
                filter: {
                    //name: 'M'       // initial filter
                }
            }, {
                total: data.length, // length of data
                getData: function($defer, params) {
                    // use build-in angular filter
                var filteredData = params.filter() ?
                    $filter('filter')(data, params.filter()) :
                    data;
                var orderedData = params.sorting() ?
                    $filter('orderBy')(filteredData, params.orderBy()) :
                    data;                    
                    $defer.resolve(orderedData.slice((params.page() - 1) * params.count(), params.page() * params.count()));
                }
            });
        })
</code>

**Comment by snowping** [comment]
One other way is to define a custom template-header and then include the filtering markup.

`````
                <table ng-table="vm.tableParams" template-header="sample_ng_header" show-filter="true" class="table table-condensed table-bordered">
                    <tbody>
                        <tr ng-repeat="user in $data">
                            <td ng-repeat="column in vm.tableColumns" ng-show="column.visible" sortable="column.field" filter="column.filter">
                                {{user[column.field]}}
                            </td>
                        </tr>
                    </tbody>
                </table>
`````
````
<script id="sample_ng_header" type="text/ng-template">
    <tr>
        <th ng-repeat="column in vm.tableColumns" ng-show="column.visible"
            class="text-center sortable" ng-class="{
              'sort-asc': vm.tableParams.isSortBy(column.field, 'asc'),
              'sort-desc': vm.tableParams.isSortBy(column.field, 'desc')
            }"
            ng-click="vm.tableParams.sorting(column.field, vm.tableParams.isSortBy(column.field, 'asc') ? 'desc' : 'asc')">
            {{column.title}}
        </th>
    </tr>
    <tr ng-show="show_filter" class="ng-table-filters">
        <th ng-repeat="column in vm.tableColumns" data-title-text="column.title" ng-show="column.visible" class="filter">
            <div ng-repeat="(name, filter) in column.filter">
                <div ng-if="filter.indexOf('/') !== -1" ng-include="filter"></div>
                <div ng-if="filter.indexOf('/') === -1" ng-include="'ng-table/filters/' + filter + '.html'"></div>
            </div>
        </th>
    </tr>
</script>
````

This way there is no need for a special watch method. Here an example of the columns var: 
`````
            vm.tableColumns = [
                { title: 'ID', field: 'user_id', visible: true, filter:{ 'user_id': 'text' } },
                { title: 'Vorname', field: 'first_name', visible: true , filter:{ 'first_name': 'text' } },
                { title: 'Nachname', field: 'last_name', visible: true, filter:{ 'last_name': 'text' }}
            ];
``````

**Comment by dsaf** [comment]
Why is this closed?
