### ISSUE TITLE
ng-table row selection for only one row 

### ISSUE THREAD

**Issue by AVelu** [esvit/ng-table#194]
In the example you brought when I select another row the previous row stays highlighted
But I want when I click on another row will not be a choice on the previous row

**Comment by Rosewood99** [comment]
@mbukosky That worked great!  I added a bit more so you can deselect the row as well when you click the same row a second time.

change the table's ng-click to only:

```javascript
ng-click='changeSelection(daily)'
```

And change the script to:

```javascript
var preSelection = null;
$scope.changeSelection = function (daily) {
    if (preSelection) {
        preSelection.$selected = false;
    }
    if (preSelection == daily) {
        daily.$selected = false;
        preSelection = null;
        //console.info(preSelection);
    } else {
        daily.$selected = true;
        preSelection = daily;
        //console.info(preSelection);
    }
}
```
