### ISSUE TITLE
v0.4 - Planned Features

### ISSUE THREAD

**Issue by esvit** [esvit/ng-table#202]
If you have an opinion should look like ng-table and what features it should enter, please write it in the comments

**Comment by scottlepp** [comment]
I see some drag and drop requests here.  Here is an example of row drag/drop.  This depends on jquery-ui and ui-sortable.  http://plnkr.co/edit/A8H9t8?p=preview

**Comment by draytond** [comment]
+1 to horizontal scroll with fixed columns at the ends

**Comment by marekmand** [comment]
https://github.com/esvit/ng-table/issues/189

+ 1
