### ISSUE TITLE
jsHint error in ngTableParams; A constructor name should start with an uppercase letter

### ISSUE THREAD

**Issue by numediaweb** [esvit/ng-table#203]
If possible stick to coding best practices like the jsHint suggests.

**Comment by Light241** [comment]
This `.factory('NgTableParams', function (ngTableParams) {` wouldn't work if u use smt like ng-annotate(gulp-ng-annotate, etc),

**Comment by Kerumen** [comment]
Can be closed as https://github.com/esvit/ng-table/commit/fc3abcd7ced1dbde7001ac36af2b7809877d5784 fix this.

**Comment by portus84** [comment]
+1

**Comment by sreeraaman** [comment]
Looks like the issue still persists with v0.5.5. My code looks like this:
```javascript
$scope.tableParams1 = new ngTableParams({
        		page: 1,            // show first page
        		count: 10,          // count per page
        		sorting: {
            			parameterOrder: 'asc'     // initial sorting
	    		}
		}, 
		{
			total: data.length, // length of data
			getData: function ($defer, params) {
				var orderedData = params.sorting() ? $filter('orderBy')(data, params.orderBy()) : data;
    				$defer.resolve(orderedData.slice((params.page() - 1) * params.count(), params.page() * params.count()));
			}
		});
```

**Comment by Apercu** [comment]
What you're using is a fallback to keep older versions working. Simply change the lowercase `n` to an uppercase one.
