### ISSUE TITLE
Add support to choose the amount of visible blocks in pagination

### ISSUE THREAD

**Issue by leonardodelfino** [esvit/ng-table#206]
Could you please add support to choose the amount of visible blocks in paging.

Simply just leave this setting to be passed as parameter.

**Comment by Patrik-Lundqvist** [comment]
A parameter for this would be great!

**Comment by cboden** [comment]
Has this feature been incorporated or ignored?

**Comment by iyel** [comment]
incorporated

**Comment by cboden** [comment]
Awesome. Thanks @iyel!
