### ISSUE TITLE
Arbitrary columns don't seem to work

### ISSUE THREAD

**Issue by danishabdullah** [esvit/ng-table#210]
```html
            <table ng-table="tableParams">
                <tr ng-repeat="record in table_data">
                    <td ng-repeat="(key, value) in record" data-title="{{key}}">
                        {{value}}
                    </td>
                </tr>
            </table>
```
doesn't work. The column headers are not shown which means that nothing from the library really works.

**Comment by dilignt** [comment]
I also got stung by this - really frustrating.  Eventually I did the following type of thing

>                <table ng-table="screenTable" class="table">
>                   <tr ng-repeat="row in data">
>                        <td data-title="headers[0]" sortable="sorts[0]"> {{row.val0}} </td>
>                        <td data-title="headers[1]" sortable="sorts[1]"> {{row.val1}} </td>
>                        <td data-title="headers[2]" sortable="sorts[2]"> {{row.val2}} </td>
>                        <td data-title="headers[3]" sortable="sorts[3]"> {{row.val3}} </td>
>                        <td data-title="headers[4]" sortable="sorts[4]"> {{row.val4}} </td>
>                        <td data-title="headers[5]" sortable="sorts[5]"> {{row.val5}} </td>
>                    </tr>
>                </table>

with my dynamic function that processes the looking like this

>     function createTableData(rows) {
>        $scope.headers = ['Screen Name', "Date", "Time"];
>        $scope.sorts = ["'val0'", "'val1'", "'val2'"];
>        $scope.data = _.map(rows, function(row) {
>            return { val0:row[0],
>                val1:row[1],
>                val2:row[2] + ':' + row[3]} ;
>        });
>    }

By controlling the size of the $scope.headers and $scope.sorts array, the extra <td> elements are not rendered, so I can use the same html template for multiple different tables, with the column values referencing val0, val1, .. etc.
