### ISSUE TITLE
special URL characters are encoded twice

### ISSUE THREAD

**Issue by pixelsailor** [esvit/ng-table#214]
The line, 380: `pairs[name] = encodeURIComponent(item);` is causing URL parameters to be encoded twice, thus `?search=two words` gets encoded to `?search=two%20words` and then again to `?search=two%2520words`.

Rewriting line 380 to `pairs[name] = item;` easily solves it.

Line 378 also features encodeURIComponent(item) but I haven't checked that portion

**Comment by rpungello** [comment]
Is there a reason this was closed? I'm having the same issue.

**Comment by zhohon** [comment]
having same issue。it seems that after 0.8.3，the url params are encoded twice。
