### ISSUE TITLE
Sorting Column with Boolean Data

### ISSUE THREAD

**Issue by michas84** [esvit/ng-table#224]
Is there any possibility to sort column with boolean data? I want to display a list of documents in table, docs have 'isRead' property (value true or false).

I tried

```
$scope.tableParams = new ngTableParams(
                {
                    page: 1,
                    count: 10,
                    sorting: {
                        IsRead: 'asc'
                    }
                },
```

but it doesn't work.

**Comment by ThonyFD** [comment]
how it fix? I'm using latest versión and the sort doesn't work in all my boolean columns.

**Comment by michas84** [comment]
I did this in controller, in getData function after ajax call (the obejcts proparty to sort by is 'IsNew'):

`var orderedData = $filter('orderBy')(docs, ['-IsNew']);`
