### ISSUE TITLE
Can't wrap ngTable around ng-if

### ISSUE THREAD

**Issue by cboden** [esvit/ng-table#227]
I'm trying to conditionally have some tables depending on user input and ajax responses. I'm using dynamic columns and have an ng-table wrapped in a div with an ng-if statement. 

Even if the condition is always true it breaks the ng-table.

**Comment by cboden** [comment]
Can `ng-if` be wrapped around `ngTable` directives now?

**Comment by iyel** [comment]
No.
Have you already have found solution for this?

**Comment by christianacca** [comment]
I don't think `ngTableParams` was ever designed to be shared across different tables. So first thing I would suggest is to maintain separate `ngTableParams` per html table.

I have tested wrapping a table inside of a div with an `ng-if`. It seems to work correctly ie the table is rendered with an `ngTable` directive only when the `ng-if` evaluates true. This is working against the latest version as I speak (https://github.com/esvit/ng-table/commit/016827745bd618aeafc16f4deaa855b29452626a = a few commits ahead of v0.5.5)

I extended demo26.html like so:

```` html
    <p><label>Include table
        <input type="checkbox" value="false" ng-model="includeTable"/>
    </label></p>

    <div ng-if="includeTable">
        <table ng-table="tableParams" show-filter="true" class="table">
            <tr ng-repeat="user in $data">
                <td data-title="'Name'" sortable="'name'" filter="{ 'name': 'text' }">
                    {{user.name}}
                </td>
                <td data-title="'Age'" sortable="'age'" filter="{ 'age': 'text' }">
                    {{user.age}}
                </td>
            </tr>
        </table>
    </div>
````

**Comment by Ebram-Tharwat** [comment]
@christianacca , it doesn't work. Can you please post a codepen of your try?
