### ISSUE TITLE
getData called more than once, why?

### ISSUE THREAD

**Issue by vedmack** [esvit/ng-table#228]
Hi,
For some reason when getData use angular resource to bring data the getData function being called twice, causing the resource to do it REST request twice <--- bad...

Any idea how to solve it?

Here a working testcase/plunker http://plnkr.co/edit/o23EXi?p=preview example that recreates this scenario (look at the browser console - "getData being called...." displayed twice ) b.t.w as you can see I'm not really using the resource to bring real data, just to demonstrate the scenario, In my real app I do use the resource to bring real data and its being called twice just like in this exaple,

Thanks ahead,

Daniel.

**Comment by sajithk** [comment]
This happened to me with a weird reason. getData get called twice on init (first load) only. changing page or sorting didn't call getData twice. The reason was that at init the ng-table directive was hidden in the template file.
