### ISSUE TITLE
Sorting problem after grunt build

### ISSUE THREAD

**Issue by muhlegg** [esvit/ng-table#230]
Sorting wont work after 'grunt build', I assume it is the js-minify that somehow breaks it. Nothing happens when I click a header. Strange though that everything else works. Anyone with similar problems?

Here's my directive controller

``` javascript
controller: ['$scope', '$filter', 'ScoresAPI', 'ngTableParams', function($scope, $filter, ScoresAPI, ngTableParams)
{
    ScoresAPI.getLeagueStandings($scope.leagueId)
        .success(function(data)
        {
            $scope.tableParams = new ngTableParams({
                page: 1,
                count: data.length,
                sorting: false
            }, {
                total: data.length,
                counts: [],
                getData: function($defer, params)
                {
                    var orderedData = params.sorting() ? $filter('orderBy')(data, params.orderBy()) : data;
                    $defer.resolve(orderedData.slice((params.page() - 1) * params.count(), params.page() * params.count()));
                }
            });
        });
}]
```

**Comment by alkrauss48** [comment]
changing `collapseBooleanAttributes` in the Gruntfile to false still fixes this issue - thanks for finding that.

**Comment by lowe0292** [comment]
+1 to @faisalferoz's workaround.

**Comment by cleargif** [comment]
Had this issue today.

No change to the grunt file `collapseBooleanAttributes: true`

This sorted it: `sortable` => `data-sortable`

**Comment by carrchr** [comment]
I resolved this issue by changing `collapseBooleanAttributes:` to `false` in Gruntfile's `htmlmin.dist.options`

**Comment by Jony-Y** [comment]
I actually had to do two things... change the `collapseBooleanAttributes:` to `false` and also change the code from `<td data-title="'App score'" sortable="'gender'"  >{{content.gender}}</td>` to `<td sortable="'gender'" data-title="'App score'" >{{content.gender}}</td> ` working with data-sorting alone did not fix for me...

**Comment by carrchr** [comment]
@Jony-Y that's odd. So you had to switch the order of how you specified the ngTable attributes in the `<td>` elements?

**Comment by joandervieira** [comment]
Great, that solved my problem as well. Thanks!

**Comment by diablofong** [comment]
I am change ```collapseBooleanAttributes: true ``` to ```false``` , the sorting can work  , Thank you

**Comment by avandecreme** [comment]
Both solutions worked for me.
However I was having a CSS issue as well (see the 2 up arrows on not sorted columns):
![ng-table-css-min](https://cloud.githubusercontent.com/assets/465389/9064920/d3174526-3a9c-11e5-8e5a-752cd4d2243b.png)

Setting the following option fixed the issue:
```javascript
        cssmin: {
            options: {
                advanced: false
            }
        },


```

**Comment by vicky-gonsalves** [comment]
@avandecreme +1   It worked for me too!

**Comment by andreicristianpetcu** [comment]
I'm glad it worked :D

**Comment by willnew** [comment]
changing collapseBooleanAttributes solved my problem, thx

**Comment by PauloF** [comment]
Using data-sortable worked for me.

**Comment by floripaoliver** [comment]
Change to the grunt file collapseBooleanAttributes: true made it work again in a second.

This did not help me at all: sortable => data-sortable

thx for the tips guys...

**Comment by suelinton** [comment]
> htmlmin

Solved for me.
