### ISSUE TITLE
Sort arrows missing on dynamic columns

### ISSUE THREAD

**Issue by cboden** [esvit/ng-table#231]
When comparing [Example 3](http://bazalt-cms.com/ng-table/example/3) with [Example 20](http://bazalt-cms.com/ng-table/example/20) the directional arrows (asc/desc) are missing when using dynamic columns.

**Comment by SebiH** [comment]
For anyone like me trying to find out why this won't work any longer:

As of v 0.5.3 the indicator has changed from div to the ".sort-indicator" class. Here is a working plnkr (I've copied the files over into Plunker as the CND does not seem to be updated yet?)
http://plnkr.co/edit/SfEW1n?p=preview

The examples should be probably updated to the newest versions and documentation should be added.

**Comment by aszmyd** [comment]
@SebiH +1 
Please update the examples.

**Comment by matisoffn** [comment]
@SebiH I've copied this exact code into my Angular app and still no icons.

ng-table v0.5.3
angular 1.2.28

Any idea?

**Comment by SebiH** [comment]
No idea, sorry - maybe something overriding the `sort-indicator` CSS class? Even a simple

    <table class="ng-table" style="height: 50px;">
      <th class="sortable">
        <div class="sort-indicator"> </div>
      </th>
    </table>

Should show the indicators in 0.5.3+, even without any js files (see: http://plnkr.co/edit/NJsSIt?p=preview )

**Comment by batjko** [comment]
I'm having the same issue, also with `ng-table-dynamic` (not using any `<th>`, just `<tr>`).

```html
<table ng-table-dynamic="ctrl.tableParams with ctrl.selectedCols" class="table exportable table-condensed table-bordered table-striped">
  <tr ng-repeat="row in $data">
    <td ng-repeat="col in $columns">{{row[col.field] | cellFormat:col.id}}</td>
  </tr>
</table>
```
The columns are set dynamically, so I'm not sure where I am supposed to add the sortable indicators?

**Comment by sandip8600** [comment]
@batjko did you find answer to your query. I have same issue

**Comment by batjko** [comment]
@sandip8600 In my case, the arrows were missing because I didn't have the ng-table's styling included in the right place. Once I added the css link in my main app html, the arrows appeared.
