### ISSUE TITLE
Typescript example?

### ISSUE THREAD

**Issue by Myrmex** [esvit/ng-table#236]
I'm trying to move from ng-grid to this library, which looks much more Angular-oriented. I'd really like a simple yet completed example for using it with Typescript (injection into controller, parameters, pagination, and the like), while we wait for an eventual full definition for it at https://github.com/borisyankov/DefinitelyTyped. Could anyone provide a clue? Thanks!

**Comment by faceleg** [comment]
This was closed with no comment - is there a canonical TS definition? If so, where?
