### ISSUE TITLE
active pages are disabled

### ISSUE THREAD

**Issue by gabegorelick** [esvit/ng-table#247]
According to [bootrap's documentation](http://getbootstrap.com/components/#pagination-default), the `.active` class should be used "to indicate the current page," not `.disabled`. This is what it looks like when everything works:

![image](https://f.cloud.github.com/assets/610129/2454806/b4ab72e2-aef2-11e3-8d32-f4ec7d364d57.png)

Note how page 1 is active and the **&laquo;** button is disabled.

But ng-table looks more like this (taken from one of the pagination examples):

![image](https://f.cloud.github.com/assets/610129/2454831/269277b6-aef3-11e3-9fd7-e0c4d56ea6b2.png)

Notice how page 1 is **disabled** instead of **active**. Not only is this incorrect from a Bootstrap-purity standpoint, but it's also a usability fail since the active page is not differentiated from the disabled back button. 

Implementation-wise, it looks like ng-table uses the `active` property of a page as synonymous with `!disabled` (see the pager template: `ng-class="{'disabled': !page.active}"`).

Potential solution: add a `disabled` property to the page object and correct the semantics of the `active` field. This will break backwards compatibility for any custom templates though.

**Comment by Kerumen** [comment]
Can be closed as https://github.com/esvit/ng-table/commit/d6bdcb18ab3810ea6d5e0496a5dc85ad2dac3002 fix this.
