### ISSUE TITLE
Examples seem to list incorrect dependency name

### ISSUE THREAD

**Issue by lalanotlistening** [esvit/ng-table#266]
I'm new to Angular, so forgive me if this is totally wrong, but the examples show something similar to this:

var app = angular.module('main', ['ngTable']).controller('DemoCtrl', function($scope, $filter, ngTableParams) {
...

And that throws this error: Error: [$injector:unpr] Unknown provider: ngTableProvider <- ngTable

Changing 'ngTable' to 'ngTableParams' worked. Is this what the examples should say, or am I missing something?

**Comment by CaptainLexington** [comment]
I had the exact same issue and the same solution presented itself. I trust the maintainer that this is not a bug, but I am extremely curious as to the explanation.

**Comment by iv301vi** [comment]
This continues to be an issue for me as well.  

Am curious as to status & resolution, if any.  
I am not new to Angular & using AngularJS 1.2.24 and the most recent nuGet package of ngTable.   

No matter how I inject of reference ngTable, I keep getting same  Error: [$injector:unpr] Unknown provider: ngTableProvider <- ngTable

Thank you for your time.

**Comment by deslauriersp** [comment]
I had the exact same issue and the same remedy worked.

**Comment by kunjanray** [comment]
Thank the lord I finally found this post..I should have paid more attention to the 'understanding controllers' section of the AJ dev guide, particularly setting up the initial state. This solved all my problems. Here's my full code for others

app.controller('DemoCtrl', ['$scope', '$filter', '$sce', 'ngTableParams', function  ($scope, $filter, $sce, ngTableParams){

**Comment by herrminni** [comment]
I looked at some demos on Codepen, and it seams, that the name has changed:
It is now `NgTableParams` with a big `N` at the beginning.

**Comment by kronus** [comment]
Thanks @herrminni changing to NgTableParams to a capital "N" worked for me. My code had been working since sometime last year and I had not changed anything, which lead to me to suspecting that one of the libraries that I was using had changed. Thank you for validating my initial thoughts and giving me a solution to my issue 

Proof that it works [http://kronusproductions.com/songs_angular/#](url)

**Comment by bonfimtm** [comment]
In order to use NgTable module you need to follow the steps in [http://ng-table.com][1]

Mind that `NgTableParams` injection is with **capital N**


  [1]: http://ng-table.com
