### ISSUE TITLE
Grouping and group order

### ISSUE THREAD

**Issue by Bhaall** [esvit/ng-table#280]
Is it possible to specify a specific grouping to always appear first?

In the Grouping example, items are grouped by Administrator, Moderator and User.

One page one, the group Administrator appears first.
On page two, the group User appears first.

This appears to be controlled by the number of items within each group.  But is it possible to override this and specify a group to always be first (if records exist in that group) on every page?

**Comment by jeyathilak** [comment]
was wondering if we have a solution to the above group order problem in grouping. if I have pagination, on each page, the group order is jumbled :(
