### ISSUE TITLE
ng-table resizing feature

### ISSUE THREAD

**Issue by douglaspeng** [esvit/ng-table#313]
Hi, dear engineer, I am just wondering if  you guys ever think about adding the resizing column feature like ng-grid, thanks!

Doug

**Comment by YvanDaSilva** [comment]
@dylamite This is a good solution, however it does add requirement for jQuery and filters are not working (The header row to do filtering is not added properly).

I made it work by manually creating the filters like the following row in <thead>.
```
		<tr class="ng-table-filters ng-scope">
			<th class="filter ng-scope">
				<input
					ng-change="table_params.filter({'column_name': table_params.filter().column_name})"
					ng-model="table_params.filter().column_name"
					class="input-filter form-control ng-scope ng-pristine ng-valid"
					type="text">
			</th>
		</tr>
```

**Comment by pelizza** [comment]
Working plunker: http://plnkr.co/edit/syWBUA7KUIhIckV0VnW3?p=preview

**Comment by Manasa74** [comment]
@pelizza tried using it the same way in plunker but getting the following error
**Controller 'ngTable', required by directive 'ngTableResizableColumns', can't be found**

Can anyone help me out of this

added the ng-table and ng-table-resizing-columns in index file

<script src="bower_components/ng-table/dist/ng-table.min.js"></script>
<script src="bower_components/ng-table-resizable-columns/ng-table-resizable-columns.js"></script>

**Comment by pelizza** [comment]
@Manasa74 have you loaded angular before both of them?

I probably can help a bit more if you could paste your code on Plunker...
