### ISSUE TITLE
Add an option to not display the footer/pagination

### ISSUE THREAD

**Issue by rand0mbits** [esvit/ng-table#338]
If there is just one "page", the footer should not be displayed at all. Maybe there can be "showFooterForOnePage" option or something. If my tables contain a small amount of records, I end up with a 61px high empty block.

**Comment by RoboSparrow** [comment]
+1,  much needed config

**Comment by AlexSchuetz** [comment]
+1

**Comment by ldunca** [comment]
+1. Thank you.

**Comment by jengwood** [comment]
+1

**Comment by AlexSchuetz** [comment]
You can provide an own pagination template like this:
 
```html
<table ng-table="tableParams" template-pagination="myOwnPaginationTemplate.html">
...
```

I am using the `ng-table/pager.html` template and only modified the following part:

Original element:
```javascript
<div class="ng-cloak ng-table-pager" ng-if="params.data.length">
```
Replacement
```javascript
<div class="ng-cloak ng-table-pager" ng-if="params.total() > params.count()">
```

Like that the pagination is only shown, if the data doesn't fit in one page. (With the sideeffect, that you can't change the pagesize. But why should you want to?)

If you want this behaviour on all your ngTables you can use the following code to replace the default template used for pagination like this:

```javascript
app.run(function($templateCache) {
            $templateCache.put('ng-table/pager.html', '<div class="ng-cloak ng-table-pager" ng-if="params.total() > params.count()"> <div ng-if="params.settings().counts.length" class="ng-table-counts btn-group pull-right"> <button ng-repeat="count in params.settings().counts" type="button" ng-class="{\'active\':params.count()==count}" ng-click="params.count(count)" class="btn btn-default"> <span ng-bind="count"></span> </button> </div> <ul class="pagination ng-table-pagination"> <li ng-class="{\'disabled\': !page.active && !page.current, \'active\': page.current}" ng-repeat="page in pages" ng-switch="page.type"> <a ng-switch-when="prev" ng-click="params.page(page.number)" href="">&laquo;</a> <a ng-switch-when="first" ng-click="params.page(page.number)" href=""><span ng-bind="page.number"></span></a> <a ng-switch-when="page" ng-click="params.page(page.number)" href=""><span ng-bind="page.number"></span></a> <a ng-switch-when="more" ng-click="params.page(page.number)" href="">&#8230;</a> <a ng-switch-when="last" ng-click="params.page(page.number)" href=""><span ng-bind="page.number"></span></a> <a ng-switch-when="next" ng-click="params.page(page.number)" href="">&raquo;</a> </li> </ul> </div> ');
        });
```

Please let me know what you are thinking of this workaround.

(I am using 0.5.4)

**Comment by viniciuspires** [comment]
Thank you, Alex. That is the best workaround by now, I almost forgot about
this feature...

Still, I think  no-pagination should be standard, and the functionality
should be composable...

**Comment by AlexSchuetz** [comment]
@viniciuspires I agree with that.

**Comment by yan-kisen** [comment]
@AlexSchuetz  Thanks, that's very clever.

In your opinion, do you think this approach is worth the extra configuration over something like this?

```
<style>
.ng-table-pager {
    display: none;
}
.custom-pagination .ng-table-pager {
    display: block;
}
</style>

<div ng-table-pagination="tableParams" template-url="'ng-table/pager.html'" ng-if="params.total() > params.count()" class="custom-pagination"></div>
```

It seems as thought the end result is essentially same, because we still end up loading an unnecessary pager, but I feel as though it's a bit cleaner. Not only do we not duplicate/overload the library template HTML for a single attribute, but we also don't pollute the run block  for the sake of hiding an element.

**Comment by morph85** [comment]
Use this to hide pagination section.

    <script type="text/ng-template" id="removePagerRow.html">
        
    </script>
    ...
    ...
    <table ng-table="params" template-pagination="removePagerRow.html" ...>
    ...
    </table>
