### ISSUE TITLE
Another Problem with require.js and ngtable

### ISSUE THREAD

**Issue by jwu009** [esvit/ng-table#340]
I am using ngtable with requires.js and got the following error:
TypeError: angular is undefined in line 49, var app = angular.module('ngTable', []);

I have the requirejs configure like this:
require.config({	
	paths: {
                'angular': "../Scripts/angular",
                'angular-route': "../Scripts/angular-route",
		'ng-table': "../Scripts/ng-table",
                ...
        },
        shim: {
                'angular': ['jquery'],
		'angular-route': ['angular'],
                'ng-table': "../Scripts/ng-table",
                ...

The result htmp page head shows angular.js is before ngTable. Why 'angular' is undefined in ngtable.js?

Thanks,

jwu

**Comment by nbppp2** [comment]
I'm hoping you already figured this out. Just in case, the value of the property 'ng-table' in your shim object should be
```
['angular']
``` 
not 
```
"../Scripts/ng-table"
```

Thus you end up with 

```
require.config({

paths: {
'angular': "../Scripts/angular",
'angular-route': "../Scripts/angular-route",
'ng-table': "../Scripts/ng-table",
...
},
shim: {
'angular': ['jquery'],
'angular-route': ['angular'],
'ng-table': ['angular'],
...
```

Hope this helps.

**Comment by yehiaa** [comment]
don't forget to export angular in shim otherwise u'll get angular' is undefined
