### ISSUE TITLE
Reordering rows

### ISSUE THREAD

**Issue by mikehaas763** [esvit/ng-table#357]
Would anyone be interested in an interface that allows rows to be reordered by the user?

**Comment by MayberryRails** [comment]
Yes very much so...

**Comment by burakkilic** [comment]
I have implemented an interface for my project, but no time to write a plunker

**Comment by MayberryRails** [comment]
burakkilic do you plan on contributing it back to the project?

**Comment by burakkilic** [comment]
Yes, but for now I am pretty busy.
