### ISSUE TITLE
Eaxmple #20 Dynamic headers doesn't work inside transclude

### ISSUE THREAD

**Issue by celestinoramalho** [esvit/ng-table#363]
Hi there.

I was trying to use ng-table (great directive btw) in a directive of mine, to use along with form, et. This directive required that columns are dynamic, but once i put de ng-table inside a transclude, the headers ng-repeat stops working, although i can "see" the columns object and even print it's length as a header.

I created a fork from your example that can be seen on http://plnkr.co/edit/mjYVEf

Is this  known issue?

Best regards,
Celestino Ramalho

**Comment by shulcsm** [comment]
Why is this marked as closed?
