### ISSUE TITLE
Error: [$injector:unpr] Unknown provider: ngTableParamsProvider <- ngTableParams

### ISSUE THREAD

**Issue by prateekcs0078** [esvit/ng-table#364]
I am trying to use ng-table and tried adding it on many places but its giving error for all cases.

When I am adding 'ngTable' in app.js, its giving "Error: [$injector:unpr] Unknown provider: ngTableParamsProvider <- ngTableParams"

When I am adding 'ngTable' in controller, its giving undefined is not a function for controller.

How should I resolve it?

**Comment by pablorsk** [comment]
I have the same problem, but I can't follow your comment:

```javascript
'use strict';
// Controller naming conventions should start with an uppercase letter
function TableCtrl($scope,  NgTableParams) {
    $scope.testVar = 'This my test for ngtable';

    // var self = this;
    var data = [{name: 'Moroni', age: 50} /*,*/];
    $scope.tableParams = new NgTableParams({}, { dataset: data});
}

// $inject is necessary for minification. See http://bit.ly/1lNICde for explanation.
TableCtrl.$inject = ['$scope', 'NgTableParams'];
module.exports = TableCtrl;
```

Regards...

**Comment by bonfimtm** [comment]
In order to use ngTable module you need to follow the steps in [http://ng-table.com][1]

Mind that `NgTableParams` injection is with **capital N**


  [1]: http://ng-table.com
