### ISSUE TITLE
Filtering a complex property is broken when using AngularJS v1.2.21

### ISSUE THREAD

**Issue by craggsi** [esvit/ng-table#388]
Here's how to reproduce:-

Edit the Demo 4 example (Table with filters). Add an additional 'Status' property to each data row.  Note this is a complex object property:-

var data = [{name: "Moroni", age: 50, Status: { Id:1, Description: 'AVAILABLE' }},
                        {name: "Tiancum", age: 43, Status: { Id:1, Description: 'AVAILABLE' }},
                        {name: "Jacob", age: 27, Status: { Id:1, Description: 'AVAILABLE' }},
                        {name: "Nephi", age: 29, Status: { Id:1, Description: 'AVAILABLE' }}];

Finally, edit the HTML table to include an additional column as shown below:-

"< td data-title="'Status'" filter="{ 'Status.Description' : 'text' }" >
  {{user.Status.Description}}
< /td >"

When using AngularJS v1.2.0-rc.2, the filter works for both the simple property (name) and the complex property, however when you reference AngularJS v1.2.21, the filter dismisses valid Status Description entries and so all rows are filtered out.

For example, the filter { "Status.Description": "av" } should return all data rows, but instead all rows are filtered out.

No errors are shown in the browser console.

**Comment by hendricius** [comment]
@iyel fixed this in master?

**Comment by iyel** [comment]
@hendricius I was closing issues just to understand which of them are still relevant.
Please read https://github.com/esvit/ng-table/blob/master/README.md#submitting-an-issue
