### ISSUE TITLE
Any examples in ng-table that shows a date range filter menu on a column header?

### ISSUE THREAD

**Issue by britirie** [esvit/ng-table#405]
Looking to choose which grid framework that is easy to implement a date column that has a filter menu that displays a date range?  Please let me know if it is possible to do in ng-table in order for my team to make a decision on which grid to use.

**Comment by texas697** [comment]
has anyone figured this out?

**Comment by seiyria** [comment]
Was wondering myself if anyone had an example of this.

**Comment by h-nasu** [comment]
I used ng-bs-daterangepicker but it was not rendering for me, so I did below to the ng-bs-daterangepicker.js file to make it render.
```javascript
$scope.$apply(function() {
  ngModel.$setViewValue({
    startDate: (moment.isMoment(modelValue.startDate)) ? start : start.toDate(),
    endDate: (moment.isMoment(modelValue.endDate)) ? end : end.toDate()
  });
  /* Added for Fix Start */
  ngModel.$render = function() {
    if (!ngModel.$viewValue || !ngModel.$viewValue.startDate) {
      return;
    }
    $element.val(formatted(ngModel.$viewValue));
  };
  /* Added for Fix End */
  ngModel.$render();
});
```

**Comment by himanshu1691** [comment]
Check if something like this help. But it is not on the column header.
http://tecdigest.com/date-range-filter-for-ng-table/
