### ISSUE TITLE
Scrolling table with fixed headers

### ISSUE THREAD

**Issue by esheffield-ivantage** [esvit/ng-table#41]
Something like this: http://www.imaputz.com/cssStuff/bigFourVersion.html

I've looked at a lot of different discussions about how to accomplish this, either through plug-ins or using CSS, but so far nothing I've found has worked quite how I would like it. My primary problem with the CSS approach is that having to apply the `display: block;` property breaks the formatting of the table, making it look ugly and unable to resize with the window. Is this a feature you've ever considered adding to ng-table? If not, do you know of the best way I can achieve this?

**Comment by divramod** [comment]
+1

**Comment by terencevs** [comment]
+1

**Comment by gitnik** [comment]
+1

**Comment by lee-40square** [comment]
+1

**Comment by brunoosilva** [comment]
+1

**Comment by covus-benjamin-schuch** [comment]
+1

**Comment by andrewboni** [comment]
Definitely +1 on this

**Comment by IronArch** [comment]
+1

**Comment by anthony-o** [comment]
+1

**Comment by EricNilsson** [comment]
+1

**Comment by dmoskovsov** [comment]
+1

**Comment by schmidtl** [comment]
+1

**Comment by incadoi** [comment]
+1

**Comment by sagarbhosale91** [comment]
I'm using angular js ng-table to display some information. I would like to make the header of the ng-table fixed with scroll bar.Moreover I need to place one accordion just before the ng-table.

When I collapse the accordion my ng-table fixed header does not work properly. Please refer plunker I have created : http://plnkr.co/edit/FGjU46cCMuhIdyacffHl?p=preview

**Comment by RomainGx** [comment]
+1

**Comment by sagarbhosale91** [comment]
Resolved with accordain ... Demo :+1:  http://plnkr.co/edit/D5XxfgH79bR2wVDhPlku?p=preview

**Comment by corbinolds** [comment]
The plugin works fine for keeping the header in place, but when resizing the page, the header retains the same width until the page is refreshed or the table is scrolled back to the top.

When looking at the accordion plunker, when i scroll down in the table and resize the page width, the header keeps the same size it had as when the page wasn't resized. http://plnkr.co/edit/FGjU46cCMuhIdyacffHl?p=preview

**Comment by devLaaziz** [comment]
+1

**Comment by lessu** [comment]
+1

**Comment by SmallDev** [comment]
+1

**Comment by theaspect** [comment]
Whoever find this, use https://github.com/jmosbech/StickyTableHeaders works out of the box

**Comment by chrispyliang** [comment]
@esheffield-ivantage 's attempt with pure css is achievable. 

After making tbody `display:block` , set all tr under tbody to `display:table` will fix the formatting issue

`thead, tbody tr {
    display: table;
    width: 100%;
    table-layout: fixed; /* even columns width , fix width of table too*/
}`

**Comment by chrispyliang** [comment]
here is an approach with pure css
```
tbody {
    max-height: 200px; 
    overflow-y: scroll;
    display: block;
}

thead, tbody tr {
    display: table;
    width: 100%;
    table-layout: fixed;
}
```
