### ISSUE TITLE
Problem with example #3

### ISSUE THREAD

**Issue by Lucas-Quintana** [esvit/ng-table#423]
Hi! I'm learning about ng-table so I'm trying to add the examples I found in your website in my code.
I copy-pasted example #3 and the sorting is not working. The initial sorting works fine but when I try to change it, fails. Any idea?

**Comment by SantjagoCorkez** [comment]
Could you provide your solution? The example 3 doesn't apply sorting (header is changed, but data rows are not sorted) if implemented as shown in example.

**Comment by SantjagoCorkez** [comment]
Ok. Addressed that too. ng-table can't sort data out-of-the-box. It's either server-side or requires manual sorting each time you use that feature.
