### ISSUE TITLE
Accessing parent scope from ng-table

### ISSUE THREAD

**Issue by zeeshanhanif** [esvit/ng-table#431]
It seems it is a bit tricky to access main controller scope within ng-table. For example, it would need to use $parent.$parent.$parent.$parent if we need to assign a value to a model value that exists in the main controller scope.

**Comment by ronny332** [comment]
+1

**Comment by ronny332** [comment]
in my case it is only $parent.$parent but the amount my be different if you use some ng-if statements where every statement creates a new scope. in my eyes a kind of shorthand to the real parent would be very helpful to implement for instance a more custom pagination template (different pages, not every time 1,2,3,4...).
