### ISSUE TITLE
Issue with reload table

### ISSUE THREAD

**Issue by eldiego34** [esvit/ng-table#444]
Hi, i have a little issue with the table reloading data, here is my controller:
<pre>
<code>
appC.controller('prodController',function($scope,$http,$location,$rootScope,$modal,ngTableParams,$filter){
  setTimeout(function(){getProductos();},100);
  var data;
  function getProductos(){
    $http.post("ajax/obtenerProductos.php").success(function(data){ 
      data = data;
      $scope.tableParams = new ngTableParams({
        page: 1,
        count: 10,
        sorting: {
            nombre: 'asc'     // initial sorting
        }
      },{
        getData: function($defer,params){
          var orderedData = params.sorting() ?  $filter('orderBy')(data, params.orderBy()) : data;
          params.total(orderedData.length);
          orderedData = orderedData.slice((params.page() - 1) * params.count(), params.page() * params.count());
          $defer.resolve(orderedData);
        }
      }
      );
    });
  }

  $scope.abrirModal = function(prod){
    var modalInstance = $modal.open({
      templateUrl: 'partials/modalProducto.html',
      controller: 'prodModalController',
      backdrop: 'static',
      resolve: {
        items: function () {
          return prod;
        }
      }
    }).result.then(function(){
    },function(reason){
      if (reason !== 'cancel'){
        getProductos();
      }
    });
  }
});

appC.controller('prodModalController',function($scope,$http,$location,$modalInstance,items,ngTableParams){
  
  $scope.items = items;
  $scope.actual = angular.copy(items);
  $scope.ok = function (actual) {
      actual = JSON.stringify(actual);
      console.log(actual);
      $http.post("ajax/updateProducto.php?prod="+actual).success(function(data){
        $scope.items = "";
      });
      $modalInstance.dismiss();
  };

  $scope.cancel = function () {
    $modalInstance.dismiss('cancel');
  };

});
</code>
</pre>

Simple code, one to the table that loads the products at the start of the controll, the second is to handle the edition of the product that i select. The code works perfectly, except for one thing, when i update the database it works good in the DB but i cant see it in the table, i have to click the head of the table to update it, after i click there the table shows good, i cant do it after editing. I tried everything but i cant make it works. Any help?

Thanks in advance.

**Comment by iyel** [comment]
https://github.com/esvit/ng-table/pull/403 merged
issue fixed
