### ISSUE TITLE
Table Filtering after data filter

### ISSUE THREAD

**Issue by Cod1ngNinja** [esvit/ng-table#462]
Hi Team,
Issue 1.
When we use format the data (filter like date) and try to filter the column it doesn't work.
for eg-
< td data-title="'DOB'" sortable="'dob'" filter="{ 'dob': 'text' }">{{user.dob | date:'medium'}}< /td>
here dob will be time in milli seconds and i use a angular-filter to display it in readable form. now if I want to use column filter it doesn't work, as the filter is on dob and not on the formatted data. it is good if we can add filter on the formatted text.
I think this scenario will be faced by many users.

For this I have done a work-around and implemented this
< td data-title="'DOB'" sortable="'dob'" ng-init="user.dobString = (user.dob| date:'medium')" filter="{ 'dobString': 'text' }">{{user.dobString}}</ td>

Issue 2.
I have a reload button for my Table. It will re-fetch data from server. After implementing the above work-around, if I set the filter on this particular column and click on reload, then the table shows empty, and it works properly for other columns.

Try adding filter for "Start" column and click "Reload button" . table will not load. but then if you click clear filter, then the data will appear.

http://plnkr.co/edit/uAxJPeoac3nSEHFnrbR5

**Comment by SlippySken** [comment]
Same problem with issue 1

**Comment by uchidake** [comment]
Same problem with issue 1 and 2. Any workarounds?
