### ISSUE TITLE
Multiple column filter

### ISSUE THREAD

**Issue by platonovr** [esvit/ng-table#478]
hi all, i saw, this theme was here (https://github.com/esvit/ng-table/issues/139) , but http://embed.plnkr.co/llb5k6/preview this url doesn't work. Can anybody give me example, how to do this thing with ngTable ? 

Thanks a lot!

upd : it's available now, thx!

**Comment by emilianox** [comment]
update : http://plnkr.co/edit/JY34GS5koARNZbcB7ukI?p=preview

**Comment by christianacca** [comment]
Take a look at:

* http://ng-table.com/#/filtering/demo-multi-template
* http://ng-table.com/#/filtering/demo-api
