### ISSUE TITLE
select-multiple filter is broken

### ISSUE THREAD

**Issue by lukad** [esvit/ng-table#484]
When using select-multiple you can only select one of the possible filter values. When you select multiple values the table shows no items.

Example: http://plnkr.co/edit/iGSL8WKlWk84L2mNhQiC?p=preview

**Comment by iyel** [comment]
Check with the latest, please

**Comment by lukad** [comment]
It still doesn't seem to be working http://plnkr.co/edit/KKczcI6mJVIZdscUSfcA?p=preview

**Comment by mrwogu** [comment]
Same here. No items on multiple values.

**Comment by poilelojulien** [comment]
Same problem here.

**Comment by ccrowhurstram** [comment]
Looks like it's working in the current version. Look at this [codepen](http://ng-table.com/#/filtering/demo-customize-algorithm)

**Comment by praveenuics** [comment]
I am on same boat, @lukad did you manage to fix this issue?

**Comment by lukad** [comment]
@praveenuics I don't really remember. I'm not using Angular anymore.
