### ISSUE TITLE
One search to custom columns

### ISSUE THREAD

**Issue by platonovr** [esvit/ng-table#485]
Hi all! I use one input to filter data in ng-table. Like this : 
<input class="form-control" type="text"  ng-model="filter.$">
and in tableParams 
 var filteredData = $filter('filter')($scope.footballers, $scope.filter);

but i want to filter by custom columns, not all.

What i need to do? 
https://docs.angularjs.org/api/ng/filter/filter  i can't understand how to send some specific params to filter function

**Comment by faustlife** [comment]
it's also important for me, don't know what can I do?

**Comment by iyel** [comment]
as workaround assign same filtering input to multiple ```filter()``` function params
```js
var query = "blah blah blah";
controller.tableParamsTasks.filter()['footballerName'] = controller.tableParamsTasks.filter()['someOtherFieldInArray'] = query;
```

**Comment by faustlife** [comment]
@iyel it's cool, but "multiple filter() function params" must be dynamic. I use service for tableParams in all my controllers...
