### ISSUE TITLE
Getting an endless loop for getData()

### ISSUE THREAD

**Issue by atrishin** [esvit/ng-table#508]
This is driving me insane. My getData() passed to settings is fairly straightforward:
```javascript
	getData: function ($defer, params) {
		$http.post('https://localhost/api/test/get-data', {
			page: params.page()
		}).then(function (result) {
			params.total(result.data.total);
			$defer.resolve(result.data.items);
		}, function () {
			$defer.reject([]);
		});
	}
```
The moment this line [414] is executed in ng-table.js:
```javascript
self.data = settings.$scope.$data = data;
```
my getData() is called again right away. I simplified the line and the assignment below calls getData() again, which in turn goes back to line 414 and infinite loop is created.
```javascript
self.data = data;
```
Funny thing is, if I pass an array to a $defer.resolve() which wasn't returned by $http everything is working fine.

Thoughts anybody?

**Comment by christianacca** [comment]
Hi atrishin, if you are using the very latest version of ng-table, then at a guess it might be the commit  https://github.com/esvit/ng-table/commit/0b91bb2d535e9dd560888fc2efe45f7c962a4359 where params.data field is now being $watch'ed. This new watch will trigger the call to getData.

**Comment by iyel** [comment]
take v0.4.3
