### ISSUE TITLE
0.4.3 promise issue

### ISSUE THREAD

**Issue by QuentinFchx** [esvit/ng-table#511]
https://github.com/esvit/ng-table/blob/master/src/scripts/03-params.js#L396
What is the purpose of the $defer passed to getData if we're using the pData promise instead ?

If it's not a bug and is part of a revamp, it should not have been tagged as a patch but as a minor since it breaks the current api :)

**Comment by iyel** [comment]
@QuentinFchx can you help to investigate what was broken by example?

**Comment by QuentinFchx** [comment]
In our projects, we're using coffeescript and the last statement is returned by default.
Before the change, it wasn't an issue since the return value of the `getData` function was not used.
Now that it is used as the data promise and that it overrides the `$defer` one, we had trouble with displaying data.

**Comment by iyel** [comment]
Plunkr example will be great

**Comment by QuentinFchx** [comment]
```javascript
// Considering this snippet of code
var table = new ngTableParams({}, {
    total: 0,
    getData: function($defer, params) {
        return resource.get({
            page: params.page()
        }).$promise.then(function(data) {
            params.total(data.total);
            return $defer.resolve(data.coupons);
        });
    }
});

// v4.0.2 will pass a defer to get data that will just be resolved
this.reload = function () {
    var $defer = $q.defer();
    settings.getData($defer, this);
    $defer.promise.then(function (data) {
        // I used $defer.resolve(data.coupons);
        // which works perfectly
    });
};

// v4.0.3
this.reload = function() {
    var $defer = $q.defer(),
        pData = null;
    pData = settings.getData($defer, this); // Because I return something here
                                            // that is a promise (return resource.get[...])
    if (!pData) { // It does not use the $defer promise anymore (which is completely confusing)
        // By the way, if getData returns an object that does not have a `then` property: BOOM = API Breaking change
        pData = $defer.promise;
    }
    return pData.then(function(data) {
        // Unluckily, my custom function returned a promise
        // which resolve into '$defer.resolve(data.coupons)'
        // and this statement returns 'undefined'
        // hereby data is undefined
    });
};
```

The [current documentation](https://github.com/esvit/ng-table/wiki/Configuring-your-table-with-ngTableParams#getdata) says nothing about the type of the returned object by `getData`
Now that it's taken into account, it's an API change and the release should have been a minor and not a patch (aka 0.5.0)

BUT, now that we are discussing the change in the code:
IMO, we should not allow 2 'use-cases' for `getData`.
Let's pick one and update the documentation accordingly :)

**Comment by iyel** [comment]
@ccrowhurstram what do u think?

**Comment by ccrowhurstram** [comment]
It's a tough decision.

Breaking backwards compatibility is not something to be taken lightly. So this is why iyel choose the route he did ie support the two use-cases.

Obviously there are cases where the change still breaks the API (QuentinFchx's scenario). So clearly keeping compatibility is not really an option if the library is to move forward to perhaps a better design.

I think here and now the project is at a place where breaking changes are a little more palatable as enhancements need to be made (eg: https://github.com/esvit/ng-table/commit/60de2066b9be1a33210767783354c11004d5e042)

So I would go with introducing a breaking change:

* **Force** `getData` to return *either* an array (for in memory collections) or a $q promise for async
* `reload` should **always** return a promise - either the one returned by `getData` or a `$q.when(data)` where `getData` returns an array

How about it @iyel?

Christian

**Comment by iyel** [comment]
@ccrowhurstram you're absolutely right - breaking changes usually not what is taken lightly. I also was thinking the way you are after @QuentinFchx raised this issue.
These changes the best option to stick with.

**Comment by QuentinFchx** [comment]
Let's go for the breaking change then :)
What needs to be done:
- remove the parameter `$defer` passed to `getData`
- update documentation / tests / examples
- tag the next release as `0.5.0`(minor) and not `0.4.4`(patch) :)

**Comment by christianacca** [comment]
I would also like `reload ` to be smart enough to allow `getData` to return *either* an array containing the data or a promise.

**Comment by iyel** [comment]
@QuentinFchx 
Why do u cannot rewrite ur code from this:
```js
var table = new ngTableParams({}, {
    total: 0,
    getData: function($defer, params) {
        return resource.get({
            page: params.page()
        }).$promise.then(function(data) {
            params.total(data.total);
            return $defer.resolve(data.coupons);
        });
    }
});
```
to this
```js
var table = new ngTableParams({}, {
    total: 0,
    getData: function($defer, params) {
        resource.get({page: params.page()}, function(data) {
            params.total(data.total);
            $defer.resolve(data.coupons);
        });)
    }
});
```
If u do this way it has to work

**Comment by QuentinFchx** [comment]
Yep, this is what I did in the end :)

**Comment by andrewboni** [comment]
@QuentinFchx thanks for bringing this up, was also hitting the same issue, since I'm using CoffeeScript with implicit returns

**Comment by QuentinFchx** [comment]
You're welcome.
Closing the issue now. It's not a bug but an evolution of the api.
