### ISSUE TITLE
Source Mapping Issue

### ISSUE THREAD

**Issue by benjsicam** [esvit/ng-table#512]
Installed ng-table through bower and used the minified version on production. Getting this error though:

GET http://domain.com/lib/ng-table/dist/dist/ng-table.min.js.map 404 (Not Found)

See the "/dist/dist"

Might be caused by: //# sourceMappingURL=./dist/ng-table.min.js.map

Might need to be: //# sourceMappingURL=./ng-table.min.js.map

**Comment by jeserkin** [comment]
A workaround was to overwrite main block in my projects `bower.json` with use of `grunt-wiredep` node plugin, but it should be fixed IMO.

**Comment by ronaldheft** [comment]
+1
