### ISSUE TITLE
Examples page is not working

### ISSUE THREAD

**Issue by gilamran** [esvit/ng-table#531]
None of the examples are working

**Comment by littlebeeper** [comment]
+1 Nope they are not working.

**Comment by christianacca** [comment]
Assuming you're referring to the demoX.html files in the examples folder. If so then you need to build the source code first. This builds the dist/ng-table.js file required for the demos.

To do this, at the command line issue the following command:

`grunt`

Note: this assumes you have installed the grunt cli globally (http://gruntjs.com/getting-started#installing-the-cli)
