### ISSUE TITLE
examples are broken

### ISSUE THREAD

**Issue by Prideth** [esvit/ng-table#534]
The examples (11) etc, are broken. Only the error "Unable to connect to any application instances." is displayed.

**Comment by ivokund** [comment]
I just see "Not Found". For example: http://bazalt-cms.com/ng-table/example/12

**Comment by christianacca** [comment]
The link works for me

**Comment by ivokund** [comment]
Yep, it's fine now. Before it was "Not found" in the iframe of every example.

**Comment by christianacca** [comment]
OK thanks for confirmation. I'll close the issue

**Comment by inetfuture** [comment]
The whole example site http://bazalt-cms.com/ng-table/ now is broken, do you guys know?

**Comment by iyel** [comment]
Works for me
