### ISSUE TITLE
Accessing `$columns` from controller

### ISSUE THREAD

**Issue by ravinggenius** [esvit/ng-table#546]
```javascript
// in controller...

var data = [
	{ name: 'Susan', age: 12, address: { street: '123 S Main Street', city: 'Frederick', state: 'MD' } },
	{ name: 'James', age: 22, address: { street: '456 N Center Road', city: 'Richmond', state: 'VA' } },
	{ name: 'April', age: 32, address: { street: '789 W Cobblestone Lane', city: 'Raleigh', state: 'NC' } },
	{ name: 'Jesse', age: 42, address: { street: '731 E Aviation Boulevard', city: 'Orlando', state: 'FL' } }
];

$scope.tableParams = new ngTableParams({
	count: data.length
}, {
	getDate: function ($defer, params) {
		$defer.resolve(data);
	}
});
```

```html
<!-- in view... -->

<table ng-table="tableParams">
	<tbody>
		<tr ng-repeat="row in $data">
			<td data-title="'Name'"   sortable="'name'">{{row.name}}</td>
			<td data-title="'Age'"    sortable="'age'">{{row.age}}</td>
			<td data-title="'Street'">{{row.address.street}}</td>
			<td data-title="'City'"   sortable="'address.city'">{{row.address.city}}</td>
			<td data-title="'State'"  sortable="'address.state'">{{row.address.state}}</td>
		</tr>
	</tbody>
</table>
```

`$columns` is accessible in the view, but I'd like to access it in the controller. Something like `$scope.tableParams.$columns` would be great. Specifically I would like some way to retrieve the values of all the `sortable` attributes. For my purposes it will be fine for the controller's `$columns` to start off as an empty array and only be filled when the view's version of `$columns` is filled.

Is this currently possible? If not, is it possible to access the `sortable` attributes from the controller some other way?

**Comment by christianacca** [comment]
So adding $columns to the `NgTableParams` instance (`$scope.tableParam`) is actually problematic from a design point of view. I won't go into details (I might end up sounding very vague).

BUT, I have recently added a new directive `ng-table-dynamic` that accepts an array of columns - these columns *you* define. 

Take a look at the following examples to get a better understanding:
* https://github.com/esvit/ng-table/blob/master/examples/demo20.html
* https://github.com/esvit/ng-table/blob/master/examples/demo33.html
