### ISSUE TITLE
Dynamic columns sorting by multiple columns

### ISSUE THREAD

**Issue by kmjones77** [esvit/ng-table#548]
Example 20 does not seem to allow sorting by multiple columns

http://plnkr.co/edit/Qt9FnE?p=preview

**Comment by ccrowhurstram** [comment]
The plunker is referencing an old version of ng-table. I suspect multiple column support was in a later version of the library, hence you plunker doesn't work.

Unfortunately the official demo site has become quite stale. I've asked the project owner (@esvit) to provide some guidance on how collaborators can fix this (https://github.com/esvit/ng-table/issues/550)
