### ISSUE TITLE
Nested table becomes unsortable upon sort of outer table

### ISSUE THREAD

**Issue by Brewhaus32** [esvit/ng-table#549]
I modified an example plunker to illustrate the issue: http://plnkr.co/edit/SAQWCzSZBsO6gyZxTlDe?p=preview

Basically, if you have an ngTable inside of another ngTable and you make them both sortable, the inner table is only sortable up until the point you manually re-sort the outer table.

I named the fields differently just to verify it wasn't somehow an issue with them having the same name.

**Comment by christianacca** [comment]
This might already be fixed. The problem is the plunker is referencing old version of ng-table.

 I've asked the project owner (@esvit) to provide some guidance on how collaborators can fix this (#550).
