### ISSUE TITLE
ng-table doesn't work when parent scope is not controller

### ISSUE THREAD

**Issue by kornysietsma** [esvit/ng-table#55]
We are trying to use ng-table in a page where the controller is set on the first element (via $routeProvider routes)

However we have two ng-switch statements wrapping the table, in order to show different views when there is no data (and other alternative displays).  And ng-switch introduces a new scope.

Ng-table seems to assume that the tableParams live on scope.$parent - in our case, as each ng-switch creates a new scope, tableParams would be on scope.$parent.$parent.$parent !!

The result in our app is that initial rendering works OK, but pressing pagination buttons does nothing - the ng-click() calls updateParams() which seems to assign a new ngTableParams object to $scope.parent.tableParams - which isn't our controller's tableParams.  The original tableParams doesn't change, so no pagination happens.

**Comment by cboden** [comment]
Why was this closed without an update? Is it resolved? Is it rejected?

**Comment by iyel** [comment]
Please see https://github.com/esvit/ng-table#submitting-an-issue

**Comment by leonardoprg** [comment]
Hey guys, was solved?

I'm trying to use it with the alternative syntax controllerAs (vm = this)

I found a workaround to make it works, but would good if it was solved

Thanks
