### ISSUE TITLE
What's in the 0.5.0 release?

### ISSUE THREAD

**Issue by davisford** [esvit/ng-table#552]
Hey, we're trying to figure out if we should upgrade.  Can you drop in some release notes on what changed?

https://github.com/esvit/ng-table/releases

**Comment by iyel** [comment]
as for now you can see commits history

**Comment by davisford** [comment]
I can look at the commit history, but I still am not sure what was built and released in the 0.5.0 tag.  The commit history shows all commits, but I don't know what branch was used to build the distribution files or 0.5.0, so while I can guess, and try to checkout the source and inspect the logs and diffs of various branches and tags, it would be really helpful to just drop in some release notes.

**Comment by iyel** [comment]
it has all commits in master from v0.4.3

**Comment by egamonal** [comment]
it looks like #190 wasn't fixed.
I can still reproduce it.
