### ISSUE TITLE
Sorting Hover Artifact

### ISSUE THREAD

**Issue by mwalz** [esvit/ng-table#561]
We've recently upgraded to the latest version (0.5.4) and noticed a new artifact appearing on our tables when the cursor is hovered over column headers. 

![screen shot 2015-03-02 at mon mar 2 12 09 35 pm](https://cloud.githubusercontent.com/assets/119113/6445887/398ee972-c0d5-11e4-8b5b-9cf77fa99e20.png)

A small square appears near the column header. There is no sorting applied to the column in the HTML or in JavaScript. 

The square remains visible as long as the cursor hovers over the header and fades away in about a second when the cursor is moved outside of the header.

Any ideas what this square is?

Thanks.

**Comment by jsJunky** [comment]
I noticed this in IE9 but not with chrome. When it sets the title attribute in the <th> elements it is doing so with a space. Changing this from ' ' to '' fixed the issue for IE9. Haven't gone through and tested with all browsers to know if the title attribute on a <th> element will cause issues if it is an empty string.

var defaults = {
        'class': function(){ return ''; },
        filter: function(){ return false; },
        filterData: angular.noop,
        headerTemplateURL: function(){ return false; },
        headerTitle: function(){ return ' '; }, // Offending code. Line 697 of ng-table.js
        sortable: function(){ return false; },
        show: function(){ return true; },
        title: function(){ return ' '; },
        titleAlt: function(){ return ''; }
    };

**Comment by dschulten** [comment]
One can specifically set the title attribute by adding "header-title" with a double quoted + single quoted value to the td:

<table ng-table class="table">
    <tr ng-repeat="user in users">
      <td data-title="'Name'" header-title="'Foo'">{{user.name}}</td>
      <td data-title="'Age'" header-title="'Bar'">{{user.age}}</td>
    </tr>
  </table>

The header-title value on the td and all other defaults are evaluated in the [directive definition](https://github.com/esvit/ng-table/blob/master/dist/ng-table.js#L825) and win over the defaults mentioned by jsJunky.

**Comment by christianacca** [comment]
Those default's no longer have include the whitespace mentioned: https://github.com/esvit/ng-table/blob/master/src/scripts/04-controller.js#L192

So not a problem now
