### ISSUE TITLE
Duplicate thead element on table

### ISSUE THREAD

**Issue by AlexSchuetz** [esvit/ng-table#574]
I am using ng-table version 0.5.4.
I am defining my own header like this (in fact I have more than one usecase for a costum-header:

```html
<table ng-show="true" ng-table="tableParams" class="table table-condensed">
      <thead ng-hide="true"></thead>
      <tr ng-repeat="item in $data">
              <td width="100%">
                     <span>{{item.label}}</span>
              </td>
      </tr>
</table>
```

but the html looks like this:

```html
<table ng-show="true" ng-table="tableParams" class="table table-condensed ng-scope ng-table">
  <!-- ngInclude: templates.header -->
  <thead ng-include="templates.header" class="ng-scope">
    <tr class="ng-scope">
      <!-- ngRepeat: $column in $columns -->
      <th title=" " ng-repeat="$column in $columns" ng-class="{ 'sortable': $column.sortable(this), 'sort-asc': params.sorting()[$column.sortable(this)]=='asc', 'sort-desc': params.sorting()[$column.sortable(this)]=='desc' }" ng-click="sortBy($column, $event)" ng-show="$column.show(this)" ng-init="template=$column.headerTemplateURL(this)" class="header"> 
        <!-- ngIf: !template -->
        <div ng-if="!template" ng-show="!template" class="ng-table-header ng-scope" ng-class="{'sort-indicator': params.settings().sortingIndicator=='div'}">
          <span ng-bind="$column.title(this)" ng-class="{'sort-indicator': params.settings().sortingIndicator=='span'}" class="ng-binding sort-indicator"> </span>
        </div>
        <!-- end ngIf: !template -->
        <!-- ngIf: template -->
      </th>
      <!-- end ngRepeat: $column in $columns -->
    </tr>
    <tr ng-show="show_filter" class="ng-table-filters ng-scope ng-hide">
      <!-- ngRepeat: $column in $columns -->
      <th data-title-text=" " ng-repeat="$column in $columns" ng-show="$column.show(this)" class="filter ng-scope">
        <!-- ngRepeat: (name, filter) in $column.filter(this) -->
      </th>
      <!-- end ngRepeat: $column in $columns -->
    </tr>
  </thead>
  <thead ng-hide="true" class="ng-hide"></thead>
  <tbody>
    <!-- ngRepeat: item in $data -->
  </tbody>
</table>
```

I had a look at ng-table.js and `if ($element.find('> thead').length === 0) {` is always true.

How can I fix this?

**Comment by arraintxo** [comment]
Same trouble here!!

**Comment by LeysS** [comment]
Hi,

I've got the same problem and i made a litle hack to resolve this :

Change :
if ($element.find('> thead').length === 0) {

By : 
            var tHeadElement = $element[0].querySelectorAll("thead")
            
            if (tHeadElement.length === 0) {
...

- $element[0] is your table itself
- querySelectorAll is the js native method to lookup elements

See full method code after modification : 

    this.compileDirectiveTemplates = function () {
        if (!$element.hasClass('ng-table')) {
            $scope.templates = {
                header: ($attrs.templateHeader ? $attrs.templateHeader : 'ng-table/header.html'),
                pagination: ($attrs.templatePagination ? $attrs.templatePagination : 'ng-table/pager.html')
            };
            $element.addClass('ng-table');
            var headerTemplate = null;
            
            var tHeadElement = $element[0].querySelectorAll("thead")
            
            if (tHeadElement.length === 0) {
                headerTemplate = angular.element(document.createElement('thead')).attr('ng-include', 'templates.header');
                $element.prepend(headerTemplate);
            }
            var paginationTemplate = angular.element(document.createElement('div')).attr({
                'ng-table-pagination': 'params',
                'template-url': 'templates.pagination'
            });
            $element.after(paginationTemplate);
            if (headerTemplate) {
                $compile(headerTemplate)($scope);
            }
            $compile(paginationTemplate)($scope);
        }
    };


Regards

**Comment by arraintxo** [comment]
In fact, a simpler change as changing `'> thead'` with `'thead'` seems to work. 

I guess the problem here is [jqlite's lack of support](https://code.google.com/p/jqlite/wiki/UsingJQLite) for [child selectors](http://www.w3.org/TR/CSS21/selector.html#child-selectors).

I haven't tried, but just linking jquery before angularjs on document's `head` section should also work to fix the problem.

Anyway I think the best fix should be the stated change to avoid an unnecessary jquery dependency.

**Comment by stephanme** [comment]
'> thead' was introduced by #434 in order to support nested tables.

Still, it would be good if ng-table would work without requiring jquery.

**Comment by christianacca** [comment]
Being lazy here... what is the "pure js" code that will select the `thead` element that is the direct child of the `$element`?
