### ISSUE TITLE
Ajax get data(+ server side pagination) problem

### ISSUE THREAD

**Issue by RomeroDiver** [esvit/ng-table#581]
Hi,
I have a problem with server side pagination. I am loading paged data from server. The data loads correct, however the display of the data is strange:
e.g. when I move from page 1 to page 2, I can see the data from page one on the bottom of the list  for a brief moment, than it disappears. On the example there is no such behavior, and I cannot find what is wrong with my code.
SO here is my Controller: 
```javascript
angular
		.module('ttUserList')
		.controller('UserListController', userListController);

	userListController.$inject = ['ngTableParams', 'UserList'];

	function userListController(ngTableParams, UserList) {
		var vm = this;
		var USERS_PER_PAGE = 10;

		vm.tableParams;
		vm.getData = getData;
		activate();

		function activate() {
			vm.tableParams = new ngTableParams({
				page: 1,
				count: USERS_PER_PAGE,
				sorting: {
					name: 'asc' //initial sorting
				}
			}, {
				total: 0,
				getData: getData
			})
		}

		function getData($defer, params) {
			UserList.getUsersPage(params.url()).then(function (users) {
				params.total(users.total);
				$defer.resolve(users.list);
			});
		}
	}
```
Html is very simple:
```html
	<table data-ng-table="userList.tableParams"  data-show-filter="true" class="bordered responsive-table hoverable">
		<tbody>
			<tr data-ng-repeat="user in $data">
				<td data-title="'Name'" data-sortable="'name'"
					filter="{ 'name,surname': 'text' }">{{user.name}} {{user.surname}}</td>
				<td data-title="'Login'" data-sortable="'login'"
					filter="{ 'login': 'text' }">{{user.login}}</td>
				<td data-title="'Location'" data-sortable="'location'"
					filter="{ 'location': 'text' }">{{user.location}}</td>
				<td data-title="'Details'">
					<md-button class="md-raised md-primary" data-ui-sref="users.details({id: user.id})" data-translate>DETAILS</md-button>
				</td>
			</tr>
		</tbody>
	</table>
```

The data that comes from the service is correct. Does anyone see any problem here?

**Comment by carlosCeron** [comment]
i have the same problem, the first time load perfect, but when send the request to server using pagination Not show data, but the data come from server correctly, only ng-table no show data, please help with this issue Thanks.

**Comment by carlosCeron** [comment]
Solve my issue with this change 

$defer.resolve(data.slice((params.page() - 1) * params.count(), params.page() * params.count()));

with this, 
$defer.resolve(data);

the pagination come from server no need data.slice() to create pagination

**Comment by keshvari** [comment]
Thank u carlosCeron . You saved my time.
