### ISSUE TITLE
what is $data on html?

### ISSUE THREAD

**Issue by johnsmeeth** [esvit/ng-table#587]
Hi Mr.
I just clone ngTable to use but in the html view i don't understant what is $data, is it returned by getData function on ngTableParams in controller? 
Thank man.

**Comment by rafialikhan** [comment]
You use ng-table="tableParams"  and in the controller define the tableParams, its properties and load the data....this creates a local data mapped to this tableParams and stores it in $data which is what you use to show the $data in the repeat loop. However make sure you pass the data you want to display to the tableParams.

http://plnkr.co/edit/hTIUoI?p=preview

**Comment by prisonier** [comment]
And how to have several tables in one page ? Can i change the variable name that handle the data ?

**Comment by MyAn50** [comment]
Thanks for explaining, I couldn't find it at Angular's document.

These kind of un-documented thing sometimes can make us crazy.

**Comment by christianacca** [comment]
I'm hoping to get the docs improved to cover this kind of stuff

**Comment by johnsmeeth** [comment]
@rafialikhan clear on my brain. thanks
