### ISSUE TITLE
header-class is not working any more

### ISSUE THREAD

**Issue by jlebleu** [esvit/ng-table#597]
Coming from a 3.X to last version

    <td header-class="ooooooooooooooooooo" data-title="'Name'">
                    {{user.name}}
    </td>

header-class is not applied any more

**Comment by jlebleu** [comment]
Found how it works now with 5.X, have to put class between simple quotes

Example :

    <table ng-table="tableParams" class="table ng-table-responsive">
            <tr ng-repeat="user in $data">
                <td sortable="'name'" header-class="'hdr'" title="'Name'">
                    {{user.name}}
                </td>
                <td data-title="'Age'">
                    {{user.age}}
                </td>
            </tr>
        </table>

For dynamic table use a 'class' attribute, as example below

    var usernameCol = {
          title: 'Name',
          titleAlt: 'Name',
          'class': 'hdr',
          sortable: 'name',
          filter: { name: 'select' },
          filterData: names,
          show: true,
          field: 'name'
        };

**Comment by christianacca** [comment]
Thanks for taking the time to post the answer to your own question

**Comment by se-panfilov** [comment]
@jlebleu You save my day, thx
