### ISSUE TITLE
Add a feature to hide the pagination

### ISSUE THREAD

**Issue by anthony-o** [esvit/ng-table#6]
My use case is that the client don't want pagination, only the sorting feature...
So with the current sources (once again, the .js which is on the demo site) I've used a CSS workaround :

div[ng-include="templates.pagination"] {
    display: none;
}

But perhaps you could add some property in the ngTableParams to don't use the pagination ? (more or less like the filter feature)

**Comment by AlexSchuetz** [comment]
You can provide an own pagination template like this:
 
```html
<table ng-table="tableParams" template-pagination="myOwnPaginationTemplate.html">
...
```

I am using the `ng-table/pager.html` template and only modified the following part:

Original element:
```javascript
<div class="ng-cloak ng-table-pager" ng-if="params.data.length">
```
Replacement
```javascript
<div class="ng-cloak ng-table-pager" ng-if="params.total() > params.count()">
```

Like that the pagination is only shown, if the data doesn't fit in one page. (With the sideeffect, that you can't change the pagesize. But why should you want to?)

Please let me know what you are thinking of this workaround.

**Comment by raytracer1975** [comment]
To disable the pagination you need to set "total" less than "count" and the "counts" equal to an empty array as the below example.
```javascript
    $scope.tableParams = new ngTableParams({
        page: 1,   // show first page
        count: 5  // count per page
    }, {
        counts: [], // hide page counts control
        total: 1,  // value less than count hide pagination
        getData: function($defer, params) {
            $defer.resolve(data);
        }
    });
```
[here](http://plnkr.co/Cg2FrPzgYH7liFRJcMQp?p=preview) the plunker

**Comment by viniciuspires** [comment]
@raytracer1975 disabling pagination != hiding pagination.

The feature being requested is actually to don't render the html or `display:none` when it's not needed, instead of a `visibility:hidden`-like solution like the current one.

**Comment by raytracer1975** [comment]
@viniciuspires reading the @anthony-o first comment seems he wanted to disable the pagination and used to hide it by css as a workaround...

**Comment by viniciuspires** [comment]
@raytracer1975 Yep :) But the thing here is actually like I commented on https://github.com/esvit/ng-table/issues/6#issuecomment-51468016, there's no actual feature to literally "disable" the pagination. The only thing that happened was that the ng-repeat that loops through the `counts` array is empty now, and the pager thinks that there's one page only. The css container is still there taking up space, the template is still downloaded and rendered, and the Angular bindings and listeners are still being allocated into memory. A feature to disable pagination would be like:

```javascript
$scope.tableParams = new ngTableParams({}, {
  paginate: false,
  getData: function($defer, params) {
    $defer.resolve(data);
  }
});
```

... and just don't render the pagination template at all.

Don't you agree? :)

**Comment by viniciuspires** [comment]
@esvit I know you closed this issue, but how do you feel about this? PRs are welcome?

**Comment by pappucha** [comment]
For <b>Hiding the pagination</b>
 $scope.tableParams = new NgTableParams({
            page: 1,            // show first page
            count: 10000000      // count per page , Here either put a imaginary count or put maximum number of rows that you have in dataset
            //Count:data.count
        }, {
            total: data.length, // length of data
            getData: function ($defer, params) {
                // use build-in angular filter
                var orderedData = params.sorting() ?
                        $filter('orderBy')(data, params.orderBy()) :
                        data;
                orderedData = params.filter() ?
                        $filter('filter')(orderedData, params.filter()) :
                        orderedData;

                params.total(orderedData.length);
                $defer.resolve(orderedData.slice((params.page() - 1) * params.count(), params.page() * params.count()));
            }
        });


And in front end 
 /*Below one i have used stop hide the per page data reflection count*/
        .ng-table-pager {
            display: none;
        }

**Comment by xiaoyuze88** [comment]
This works fine for me.
    
    .ng-table.no-pager + div .ng-table-pager {
        display: none!important;
    }

Then you can add `.no-pager` class on the table which you want to hide the pagination.

**Comment by FabioT0** [comment]
@viniciuspires 
Totally agree, very unprofessional behaviour.

**Comment by ishamrozeraza** [comment]
in my case i had to two tables to work with. under certain condition the one is shown and the other gets hidden and vice versa. and because the pagination div is created outside the table element therefore condition to hide or show a table will only hide or show the table but once the pagination is displayed it wont hide .

So i basically wrapped the whole table in a div and set condition on the div 

`
<div ng-show="(showWaitingList || showAllUsersList) && !availabilityView">
   <table ng-table="tableParams" show-filter="true" class="table" >
   </table>
 </div>
<div ng-show="availabilityView>
   <table ng-table="tableParamsForAvailabilityView" show-filter="true" class="table" >
   </table>
 </div>
`
may be this solution could help someone..
Thanks.
