### ISSUE TITLE
Start & end symbols

### ISSUE THREAD

**Issue by popovicidinu** [esvit/ng-table#601]
Hello.

I was wondering if it's possible to configure the module so that I can change the start/end symbols used, in a similar way you can change it for angular modules by using the $interpolateProvider: 

  `$interpolateProvider.startSymbol('[[').endSymbol(']]');`

I'm using Twig as a template engine, and because it comes by default with "{{" and "}}", I changed the AngularJS symbols to "[[" and "]]". Due to this change, it seems that some elements of the table are broken (one example that comes to mind is `<th title="{{$column.headerTitle(this)}}" `). 

It would be highly useful for most people that use HTML templating engines such as Twig, Smarty, etc.

**Comment by iyel** [comment]
http://bazalt-cms.com/ng-table/example/17

**Comment by popovicidinu** [comment]
Not applicable. 

I'm not talking about how to write the elements inside the <td>'s. 

Internally, even if you use custom start & end symbols, the directive is not using them when constructing elements, such as the table header, th titles, etc.

**Comment by gwest7** [comment]
Did you ever solve this? I have the same problem with the Blade templating engine.
