### ISSUE TITLE
How to add a column on the fly for ng-table-dynamic

### ISSUE THREAD

**Issue by jlebleu** [esvit/ng-table#602]
Any idea how to add a column when the table is already created ?

Idea I have a table with 2 cols and on some condition I need to add a third column.

**Comment by ccrowhurstram** [comment]
I'm pretty sure adding a column after the table has been created is not possible.

The only way to support this at the moment to add all three columns and then use a show field on each column definition. Your third column will have it's show field set to false. Your code would then update this field to true when you want to show it.

C

**Comment by jlebleu** [comment]
I found a way, but I am not sure it is a clean way, I wrote a function to recompile a template containing the template ...... Probably this code could be inserted somewhere in ng-table as a redraw function.... If some body has a better idea.

Code snippet below

HTML file

    <div id="agtView">
        <table ng-table-dynamic="agentDynTable with cols" show-filter="true" class="table table-condensed">
            <tr ng-repeat="agent in $data">
                <td class="{{col.cellClass}} T{{agent[col.field]}}" data-header-class="'tableTitle'" ng-repeat="col in $columns"><agtfield agent="agent" arg="col"></agtfield></td>
            </tr>
        </table>
    </div>

Javascript :

    var refreshTable = function() {

        var agentViewTable = '<table ng-table-dynamic="agentDynTable with cols" show-filter="true" class="table table-condensed">' +
                                 '<tr ng-repeat="agent in $data">' +
                                     '<td class="{{col.cellClass}} T{{agent[col.field]}}" data-header-class="" ng-repeat="col in $columns"><agtfield agent="agent" arg="col"></agtfield></td>' +
                                 '</tr>' +
                              '</table>';
        var newDirective = angular.element(agentViewTable);
        var element = angular.element( document.querySelector( '#agtView' ) );
        element.empty();
        element.append(newDirective);
        $compile(newDirective)($scope);
    };

**Comment by ccrowhurstram** [comment]
I think there might be a couple of problems with that approach:

1. the `$scope` associated with the previous directive is not being `$destroy`'ed
2. the `NgTableParams` that you create in *your* controller and pass to the directive (`agentDynTable with cols`) - I worry that it will still maintain a reference to the original `$scope`
    * at best this could cause a memory leak
    * at worst you might get weird bugs where some of it's functions are still referencing the old `$scope`

Instead, my gut feeling for an approach would be for `ngTableDynamic` to use a `$watchCollection`  on the `cols` supplied. 

When the `$watchCollection` sees a change it would adjust it's internal `$columns` array. This would trigger the `ng-repeat` over the columns to "do its thing" and render out the new columns

C

**Comment by jlebleu** [comment]
Thanks for your comment, for the moment I'm doing it only once when some events are received from the server, but I will need to do it more often as the user should have the ability to change column order .... I will try to implement your idea

**Comment by banzai-samurai** [comment]
http://bazalt-cms.com/ng-table/example/20 does this answer your question?

**Comment by jlebleu** [comment]
@banzai-samurai thank you for the link by I would like to be able to display new columns once the table is already on screen, or even to be able to change column order. So example 20 is only part of the solution.

**Comment by jlebleu** [comment]
I think I start to see how to be able to do this, is to pass the col as an attribute to the directive something as cols : '=' and not getting them through the parseDirectiveExpression function. Will try to set up an example with that

**Comment by christianacca** [comment]
Got to think about backwards compatibility so you need to keep the current
expression. Think about ng-repeat it doesn't have a separate attribute to
supply the list to repeat over yet u can change the list at runtime.

You should be able to set a $watchCollection on the array after it has been
parsed...

**Comment by BartoGabriel** [comment]
One way would be to change the directive of ngTableDynamic (Now, this on https://github.com/esvit/ng-table/blob/master/src/scripts/05-directive.js#L155):


```javascript
                return function (scope, element, attrs, controller) {
                    var expr = parseDirectiveExpression(attrs.ngTableDynamic);
                    var columns = [];
                    if ($parse(expr.columns)(scope)) {
                        columns = $parse(expr.columns)(scope);
                        scope.$watchCollection(expr.columns, function () {
                            columns = $parse(expr.columns)(scope);
                            scope.$columns = controller.buildColumns(columns);
                        });
                    }
                    scope.$columns = controller.buildColumns(columns);

                    controller.setupBindingsToInternalScope(expr.tableParams);
                    controller.loadFilterData(scope.$columns);
                    controller.compileDirectiveTemplates();
                };
```
What it does is call buildColumns each time the array of columns changes.

I do not know if it's the best solution, but it works.

**Comment by jlebleu** [comment]
good trick thank you I will test it

**Comment by christianacca** [comment]
Just some feedback on that code snippet above:

Seems like there's more calls to $parse than is necessary but other than that it looks good.

To accept changes as a pull request:

1. we need a unit test for the new behaviour (see https://github.com/esvit/ng-table/blob/master/test/tableDynamicSpec.js)
2. follow the contribution guidelines (see https://github.com/esvit/ng-table/blob/master/CONTRIBUTING.md)

Thanks and good luck!

C

**Comment by BartoGabriel** [comment]
@christianacca thanks for the clarification, I can fix easily and I can also do the tests.
But, before doing my PR (I don't want to screw up.)
I would like to know:
Why it not became two way data-binding? Why they decided to create a new column object?

**Comment by christianacca** [comment]
The main motivation was to match the existing API. 

You see the ngTable directive (ie not ngTableDynamic) already had the concept of a column object but mostly this was an internal thing. This column object exposes a set of getter functions.

With the introduction of ngTableDynamic the columns supplied by a developer needed to match this existing API so that the existing code would work with these supplied columns.

However, the existing API for these columns is a bit clunky - a developer really just wants to be able to pass an object with fields that are plain values. A developer wants to change the values assigned to these fields and have standard two way data binding do its thing.

This is exactly what a developer can do - supply the column object as a simple POJO. However, in order to match the existing column API, these POJO objects are wrapped in another object that exposes the simple field values as getter functions. This is the reason why there is a new column object created.

Hopefully the above was the answer to the question you asked!

C

**Comment by jlebleu** [comment]
It works well thanks, did an example now I have to figure out how to write the test.

**Comment by jlebleu** [comment]
Did a pull request here https://github.com/esvit/ng-table/pull/623 with some tests.

**Comment by dsaf** [comment]
@ccrowhurstram 

> I'm pretty sure adding a column after the table has been created is not possible.

But how do we re-create the table? Invoking the tableParams.reload doesn't really work, as new columns are not picked up. Is there any way that can be fixed as well?

**Comment by christianacca** [comment]
Merged by https://github.com/esvit/ng-table/commit/016827745bd618aeafc16f4deaa855b29452626a
