### ISSUE TITLE
"header-class" not working in latest version 0.5.3

### ISSUE THREAD

**Issue by xalxling** [esvit/ng-table#607]
Line827:   'class': parsedAttribute('header-class'),
should be changed to:
Line827:   'class': getAttrValue('header-class'),

Check it, please!

**Comment by se-panfilov** [comment]
@xalxling worked on 0.5.4 (in case you put a class between simple quotes, like `header-class="'custom'"`)

**Comment by christianacca** [comment]
See https://github.com/esvit/ng-table/issues/597#issuecomment-117032325
