### ISSUE TITLE
Problem with dynamic header

### ISSUE THREAD

**Issue by NeevShah** [esvit/ng-table#612]
Dynamic headers don't work well with async function. 
I have a column which are coming from server. I don't work IF i try to do that.
Please check following plunker where i have reproduce the same issue. Am I doing something wrong here?

http://plnkr.co/edit/A55yMAuMgZdpSrJiWL9D?p=preview.

**Comment by christianacca** [comment]
This is a limitation - the array containing the columns need to be available at the time the ng-table-dynamic is compiled.

There are two possible solutions:

1. load the list of columns using a [route resolve](http://odetocode.com/blogs/scott/archive/2014/05/20/using-resolve-in-angularjs-routes.aspx) for the controller responsible for your view
2. wait for a pull request that looks will resolve the problem (this pull request might be coming soon as it was discussed in the following issue https://github.com/esvit/ng-table/issues/602)

**Comment by NeevShah** [comment]
@christianacca Thank you for your help.. I think I'll go with option 1 till the problem is not resolved.

**Comment by christianacca** [comment]
Cool glad I could help
