### ISSUE TITLE
parameters() function and filters

### ISSUE THREAD

**Issue by Flo-G** [esvit/ng-table#613]
Hello,

I've come across an issue when programmatically updating parameters.

Please have a look at: http://jsfiddle.net/FloG/pjs74dq4/

**By default, the name column is filtered with 'Mo'.**

**After a second, I run:**
```javascript
$scope.tableParams.parameters({page: '1', count: '10', filter: { name: 'M'}});
```
Which successfully updates the filter to 'M'.

**A second later, I run:**
```javascript
$scope.tableParams.parameters({page: '1', count: '10'});
```
Which expected behavior would be to remove the filter, but doesn't work.

**What does work, is running:**
```javascript
$scope.tableParams.parameters({page: '1', count: '10', filter: {}});
```
But it's slightly inconvenient to have to do that in my use case.

Thank you

**Comment by christianacca** [comment]
Yup, api can be a little confusing at times. However, I think if $scope.tableParams.parameters({});` removed all filters, sorting, page and page size this would also be confusing.
