### ISSUE TITLE
Dynamic data-title with ng-repeat

### ISSUE THREAD

**Issue by Ebolon** [esvit/ng-table#62]
I would like to assign the title dynamically on creation of the html element. It seem the title parser work before the assignment. If i inspect the elements in chrome the title is set but the thead element is missing.

``` html
<table ng-table="tableParams" show-filter="true" class="table table-striped">
    <tr ng-repeat="item in items">
        <td data-title="{{key}}" ng-repeat="(key, value) in item">
            {{value}}
        </td>
    </tr>
</table>
```

**Comment by CrisGarcis** [comment]
+1
