### ISSUE TITLE
bower using `' '` for default `headerTitle`

### ISSUE THREAD

**Issue by kolodny** [esvit/ng-table#620]
Do `bower install ng-table` then take a look at `bower_components/ng-table/dist/ng-table.js` on line 697 I get

```js
headerTitle: function(){ return ' '; },
```

Which means that 7daba3a never made it to bower

**Comment by psalaberria002** [comment]
bower installs the latest tag which is 0.5.4 at the moment. If you want the latest commit from the branch, you need to specify that in your bower file. You can also use the commit hash.

For latest commit in branch master:
"dependencies": {
    "ng-table": "master"
  }

For a specific commit:
"dependencies": {
    "ng-table": "7daba3a"
  }
