### ISSUE TITLE
select filter doesn't work

### ISSUE THREAD

**Issue by faisalferoz** [esvit/ng-table#625]
As per the new changes $column has been renamed to column but the select filter still refers to $column which causes the select box to appear empty. Here is the relevant code
```
ng-options="data.id as data.title for data in $column.data" ng-model="params.filter()[name]"
```
Changing the `$column` to `column` fixes the issues.

**Comment by christianacca** [comment]
Hi faisalferoz,

Can you point to the commit where the name of `$column` was changed to `column`? I can't see this myself...

Also, looking at [demo10](https://github.com/esvit/ng-table/blob/master/examples/demo10.html) this is working with the name being `$column`.

C
