### ISSUE TITLE
Custom Header ( ng-change not called in Controller)

### ISSUE THREAD

**Issue by sachindu** [esvit/ng-table#631]
Hi All,
I have a ngtable and i want to put a dropdown(select) in table header which i have done and its populating with values. I have done this by below code.
"<script type="text/ng-template" id="ng-table/headers/select.html">
                                <select name="cbDiscount" id="cmbDisc" ui-select2 style="width: 200px" ng-model="item.DiscountId"  ng-change="applyDiscount(dis)" >
                                    <option style="display: none" value=""></option>
                                    <option ng-repeat="dis in Discounts" value="{{dis.DiscountId}}">{{dis.DiscountHead}}</option>
                                </select>
                            </script>"

But when i am trying to fire ng-change applyDiscount is not getting called in the controller in which i put ng-table.

Can anyone help and guide me what should i do.

The purpose of putting dropdown in header is that we have a ngtable of items and in header i want a dropdown filled with Discounts and on selection that discount applied to all items in rows.

**Comment by hendricius** [comment]
Please post some code, then I can check. Thanks.

**Comment by sachindu** [comment]
Hello Guys, 
Actually i have put UI-Select 2 directive and place it in header of ngtable and same UI select 2 i put as column value in row.

I just changed priority of uiselect 2 in its constructor and now everything works fine for me.. 

That one was an issue of ui select 2 and not ng-table.

Thanks
