### ISSUE TITLE
How to to add row number

### ISSUE THREAD

**Issue by Kosmonaft** [esvit/ng-table#643]
Dear All,

is there any way to add number of row?
I tried with {{index}} but on each page it is reset the index/

Cheers

**Comment by christianacca** [comment]
Maybe something like:
```` html
<table ng-table="tableParams">
  <tr>
    <td>{{ (tableParams.page() * tableParams.count()) + index }}</td>
  </tr>
</table>
````

**Comment by christianacca** [comment]
I'm assuming this resolved your issue, so closing it. Chime in if that's not the case....
