### ISSUE TITLE
ng-repeat on td doesnt show column header

### ISSUE THREAD

**Issue by shyambhiogade** [esvit/ng-table#646]
hi, 
I have used ng-repeat on td element, with data-title on it, it just shows the column header only for the first column, but not for the rest of the item in the iteration. please check if its an issue.
![no header](https://cloud.githubusercontent.com/assets/10468130/8623747/00668c94-26e8-11e5-857d-a7a1e1b0a161.png)

<td data-title="'Age'" ng-repeat="a in user.age">

**Comment by christianacca** [comment]
Have you tried the latest version (0.6.0 or could be 0.7.0 by the time you read this)?

**Comment by christianacca** [comment]
Also are you using `ngTable` or `ngTableDynamic`?

**Comment by christianacca** [comment]
I'm assuming this is no longer a problem... closing
