### ISSUE TITLE
Table Header mismatch.

### ISSUE THREAD

**Issue by brianpkelley** [esvit/ng-table#647]
**Scenario:**
Had a table with 11 columns (0-10) where all but one column was sortable.  

**Problem:**
The actual data columns were ordered as the were in the body of the ng-table directive element.
`0 1 2 3 4 5 6 7 8 9 10`
The column headers were ordered as: 
`5 0 2 3 4 1 6 7 8 9 10`

Noticed that the header template is ordering the columns by "position" and the column object generated in ngTable.compile lacked a position property.

**Solution:**
Add position to the column object being pushed by ngTable.compile 
https://github.com/esvit/ng-table/blob/master/src/scripts/05-directive.js#L70

    columns.push({
        position: i,            // Use i before incremented
        id: i++,                // Use i and increment
        title: parsedAttribute('title'),
        titleAlt: parsedAttribute('title-alt'),
        headerTitle: parsedAttribute('header-title'),
        sortable: parsedAttribute('sortable'),
        'class': parsedAttribute('header-class'),
        filter: parsedAttribute('filter'),
        headerTemplateURL: parsedAttribute('header'),
        filterData: parsedAttribute('filter-data'),
        show: (el.attr("ng-show") ? function (scope) {
            return $parse(el.attr("ng-show"))(scope);
        } : undefined),
    });

I'd submit a PR but I'm currently not set up for that, my apologies

**Comment by bcody** [comment]
+1, having same issue. Everything is fine for first 10 columns, but 11+ columns have a column header in the wrong place.

**Comment by christianacca** [comment]
This was fixed in the latest version (0.7.0)

**Comment by bcody** [comment]
Ah, thanks Christian!

**Comment by rougin** [comment]
This problem also occurs in ```0.5.4``` but it doesn't have any issue in Internet Explorer.
