### ISSUE TITLE
What happened to the Plunker links

### ISSUE THREAD

**Issue by Sampath-Lokuge** [esvit/ng-table#649]
Where's the plunker links of this project ?  :confused: I cannot see it on here :http://ng-table.com/#/demo/1-1

**Comment by christianacca** [comment]
Yeah its not so great that they're gone. The owner of the repo is in the middle of creating a new website (gh-pages). Hopefully this will get added back.

In the meantime, I'm hoping to get a codepen and maybe plunker base template so that we can at least fork something...

**Comment by Sampath-Lokuge** [comment]
Thanks for the feedback @christianacca . It's huge frustration for us.B'cos removing all the good things from existing repo is really BAD.I don't know why he did that way. Pathetic  :worried:

**Comment by christianacca** [comment]
Hey Sampath, I hear your frustration. Just try not be hard on the @esvit as he's got limited time at the moment to get things to a good place in terms of documentation.

In the meantime, I've create a codepen for everyone to fork: http://codepen.io/christianacca/pen/jPxgzY?editors=101

The one above is for `ngTableDynamic` but I'm going to create another codepen soon for `ngTable`.

**Comment by Sampath-Lokuge** [comment]
Hi Christian,
Could you tell me why these links are not working ? Thanks in advance.
http://plnkr.co/users/esvit

**Comment by christianacca** [comment]
so I had a look at one of those... it links to urls that are now dead. Take
for example: http://bazalt-cms.com/assets/ng-table/0.3.1/ng-table.css -
this redirects to http://ng-table.com/#/

**Comment by Sampath-Lokuge** [comment]
Could you tell me how to fix them ? I'll fix them all @christianacca

**Comment by christianacca** [comment]
Cool.

Docs are still in flux. Not sure how the best way to get things in a
position for contributions. Let me look into it first then I'll get back to
you. In terms of timing, I hope to get onto this next week.

**Comment by christianacca** [comment]
The new [demo-site](http://ng-table.com/) has been published and replaces the plunkers,

**Comment by Sampath-Lokuge** [comment]
Wow .. Great .. Keep up the Great work Christian ! :)

**Comment by ccrowhurstram** [comment]
Thanks
