### ISSUE TITLE
Why "page" becomes "page()"?

### ISSUE THREAD

**Issue by MyAn50** [esvit/ng-table#651]
In demo1.html, $scope.tableParams has these two in the instatiation:
  $scope.tableParams = new NgTableParams({
    page: 1, count: 10}, ...

This match Configuring your table with ngTableParams (https://github.com/esvit/ng-table/wiki/Configuring-your-table-with-ngTableParams). 

However, they all referenced as:
  params.page() and params.count()

Taking out the () would NOT work. So property becomes function?

**Comment by christianacca** [comment]
You are correct - the values supplied to the `NgTableParams` constructor are exposed as getter/setter functions on the `tableParams` object.

**Comment by MyAn50** [comment]
Thanks for confirming. 
1. In the article, all examples referencing params' properties are via getter and setter. Guess this is the only to access them.
2. It is kind of confusing. Is there a particular reason?

**Comment by christianacca** [comment]
I suspect the original design was inspired by a jquery style public api
that uses the getter/setter approach
