### ISSUE TITLE
Filtering problems

### ISSUE THREAD

**Issue by TeodorKolev** [esvit/ng-table#652]
When add a function in my controller for filters, filter at ui page did not working:
filter : function(somth) { 
              if (somth.somth > $scope.somth || somth.somth > $scope.somth) {
                 return somth;
              }
              else {
                 return null;
              }
          },
UI needs to clear filtering to start working

**Comment by TeodorKolev** [comment]
Prove me that repo is not dead

**Comment by christianacca** [comment]
OK @TeodorKolev I think **you** should consider this repo as dead and start using another grid solution.
