### ISSUE TITLE
Data is not reloaded when changed in modal

### ISSUE THREAD

**Issue by martinpfannemueller** [esvit/ng-table#660]
I open a modal for editing when clicking on an entry in my table. Then I change the data and click save in the modal. The update is send as HTTP PUT to my backend (I use Restangular here in my service). My callback from the modal looks like this:
```javascript
modalInstance.result.then(function () {
     $scope.tableParams.reload();
});
```
However the data is not properly reloading. What am I doing wrong here? If I reload the whole page my data is updated. Thanks a lot!

**Comment by IgorWolbers** [comment]
Calling the reload() method re-execute the call to *getData: function ($defer, params)* that you have to define to load the data when the control is first loaded. Put a break point in your definition of *getData* and see what is happening there. The end result should be that you want the *resolve* method to be called again on the promise object *$defer* (the 1st parameter passed into *getData*), this is what actually loads the data into the table.

**Comment by martinpfannemueller** [comment]
Thanks a lot for your good explanation. Although the data got refetched it did still not refresh it. I "resolved" as seen below:
```javascript
modalInstance.result.then(function () {
     $timeout(function(){
          $scope.tableParams.reload()
     }, 100);
});
```
I am not 100% sure why this fixes it, but it has probably nothing to do with ng-table. I assume the new GET was too fast for the database since I use callbacks everywhere and the modal closes after the PUT is done. Thanks anyways!
