### ISSUE TITLE
 NgTableParams.$params gone?

### ISSUE THREAD

**Issue by atte-backman** [esvit/ng-table#666]
Since 0.8.1, after instancing NgTableParams, there isn't $params anymore as part of it.

This was possible in 0.8.0:

    var table = new NgTableParams(...);

    table.$params.page = 1;

but not anymore. I didn't find this documented anywhere? What is the current approach to achieve above?

**Comment by christianacca** [comment]
Hi atte - I think you need to stop your jibber jabber, you crazy fool :-)

Only kidding! 

Here's the commit where `$params` was removed: https://github.com/esvit/ng-table/commit/e94ca5f7873673616e15a46ab8317595331ab6e1

The equivalent *public* api for readin/writing to `$params$` is `NgTableParams.parameters`, or the more focused methods: `filters`, `sorting`, `page`, `count`

C
