### ISSUE TITLE
THEAD Found

### ISSUE THREAD

**Issue by BartoGabriel** [esvit/ng-table#670]
In compileDirectiveTemplates Function, It determines if the table already has a header.
The problem: It's called a $element.children like property, and is a function.

https://github.com/esvit/ng-table/blob/1ee441bebf3e1f8fac260a38b8b82122714191d2/src/scripts/04-controller.js#L88

It must be changed:
angular.forEach($element.children, function(e) {

To:
angular.forEach($element.children(), function(e) {

**Comment by christianacca** [comment]
Can you send a pull request and I'll merge

**Comment by BartoGabriel** [comment]
Done!

Thanks
