### ISSUE TITLE
[Suggestion] Option to apply filters only on keypress event.

### ISSUE THREAD

**Issue by chillyistkult** [esvit/ng-table#680]
So at the moment, every time I want to filter something in ng-table the filter value gets automatically applied and ng-table reloads. This is fine for static datasets, however it is horrible for heavy ajax request. Even if I would increase the filter delay it's not a good user experience overall, because it may take some time and burns resources to call our API every time the user types something in the filter input.

I would suggest to implement an option and let the developer decide if the filters are applied automatically if something changes or they apply only on certain keypress events (e.g. user hits enter).

**Comment by christianacca** [comment]
Personally, I think that debounce should be moved into the ngModelOptions and allow each filter template to then decide when / how to apply debouncing.

You can probably already achieve this if you're prepared to write your own filter templates that replaces the built in ones.
