### ISSUE TITLE
Ajax Data Loading demo not working

### ISSUE THREAD

**Issue by sweisman** [esvit/ng-table#682]
http://ng-table.com/#/demo/5-2

The above demo isn't working.

**Comment by christianacca** [comment]
Yeah those demo's are falling into disrepair.

I am in the process of rewriting the entire demo-site. Should be ready Monday next week.

**Comment by christianacca** [comment]
OK so maybe not... still working through changes before being able to complete the demo site.

In the meantime check out the codepen's that are forming the bulk of the demo-site: http://codepen.io/collection/XOLQPM/

**Comment by christianacca** [comment]
The demo site is now sufficiently complete so look there for working examples
