### ISSUE TITLE
Outdated on NPM

### ISSUE THREAD

**Issue by bvalosek** [esvit/ng-table#683]
Hi,

It seems the latest stable version (0.8.3) is not on NPM

https://www.npmjs.com/package/ng-table

Shows version as 0.5.4. Could this be updated? Thanks

**Comment by christianacca** [comment]
Once we get to 1.0.0 (next few weeks hopefully), I'm going to ask the owner to update npm

**Comment by danswater** [comment]
Is there any new update about this?

**Comment by astik** [comment]
Would also be interested on this issue. I'm relying on bower only because of ngTable, it would be great to only rely on NPM =)
Soome plugin takes care of the whole release process and npm publication like https://github.com/geddski/grunt-release ... i'll try to PR with this tool and documentation.

**Comment by gitnik** [comment]
+1 for getting it on npm

**Comment by kyrylkov** [comment]
+1 (npm is a must these days)

**Comment by carlosbaraza** [comment]
:+1:

**Comment by carlosbaraza** [comment]
@esvit, could you upgrade the npm module? People are starting to drop Bower and we have the same issue than @astik, relying on bower only because of ngTable.

**Comment by astik** [comment]
Hi @carlosbaraza ,
1s you can see in #761 @ccrowhurstram is working hard on getting this issue fixed. If you have any TypeScript knowledge, he'll be happy to have some help =)

**Comment by ramnetdevs** [comment]
Thanks @astik for trying to get the ball rolling again!

**Comment by ccrowhurstram** [comment]
... that last comment was me (@ccrowhurstram)!

**Comment by shikloshi** [comment]
+1

**Comment by TheSachin** [comment]
+1

**Comment by SlippySken** [comment]
+1

**Comment by MarcBT** [comment]
+1 also moving from bower to webpack.

**Comment by gitnik** [comment]
what? bower and webpack are not even the same thing.

**Comment by MarcBT** [comment]
@gitnik I know. Adding webpack to our project, which works fine with npm.
So to be more precise, want to use ng-table's npm package rather than bower one.

**Comment by christianacca** [comment]
1.0.0 has been published on npm
