### ISSUE TITLE
Return a promise in FilterDarta

### ISSUE THREAD

**Issue by BartoGabriel** [esvit/ng-table#687]
In the next sample, I have two tests:
* FilterData in Column 1: Return a promise, but is resolved before returning.
* FilterData in Column 2: Return a promise that is resolved two seconds later.

http://codepen.io/BartoGabriel/pen/qOBRQN

The promises in the data filter only work when they resolve before. They should be able to resolve the promise at any time, otherwise it makes no sense to use promises.

I think the problem is in the way the controller is initialized.
https://github.com/esvit/ng-table/blob/master/src/scripts/ngTableSelectFilterDs.directive.js#L54

Here you assign the variable:
`$scope.$selectData = data;`

If the promise is solved variable has a value, but not if it has not yet resolved.

**Comment by christianacca** [comment]
Yeah that doesn't look right does it. I'll try and find out what the problem is. I'm keen on solving this for the 1.0.0 release which should be happening within a week

**Comment by BartoGabriel** [comment]
OK thanks.
When I have a little time, I'll try to help you to find the problem.

**Comment by christianacca** [comment]
I had a look and I see the problem. I'll try and fix this now.

**Comment by christianacca** [comment]
https://github.com/esvit/ng-table/commit/4c0636857c804f5d050dbf83698f0615ee1216f9 fixes the problem
