### ISSUE TITLE
Update the total number of records in the config object

### ISSUE THREAD

**Issue by zoran119** [esvit/ng-table#689]
More of a question rather than an issue, but is it possible to update the `total` of `tableParams` object?

So, `tableParams` has been initialised like this:

    $scope.tableParams = new ngTableParams({
        page: 1,
        count: 10
    }, {
        total: values[0].data.length,
    });

Sometime later I'd like to do this:

    $scope.tableParams.total = 5;

**Comment by christianacca** [comment]
`$scope.tableParams.total(5)`
