### ISSUE TITLE
Required angular version

### ISSUE THREAD

**Issue by Sheldan** [esvit/ng-table#694]
I'm currently using angular 1.3.17 due to some issues of angular 1.4.x with ngAnimate. Which is an angular version supported by ngTable? Are there some older tags which support 1.3.17?

**Comment by christianacca** [comment]
What issues are you having with using ngtable with that version of angular?

**Comment by Sheldan** [comment]
The issue was, that if I simply added the js file to my index.html angular had errors and so I thought, that there is perhaps a version mismatch, because the errors itself, didn't say much. I was trying to reproduce it again, but for some reason it didn't occur again. Good for me, but sorry for wasting your time.

But I'm a bit curious, are there some lists of which versions are supported?

**Comment by christianacca** [comment]
Ok glad you don't have an issue. Not 100% sure which versions of angular is supported. I would hope 1.2.x but it might need 1.3.x

**Comment by Sheldan** [comment]
Thanks, good to know. I will close this issue then, as it works.
