### ISSUE TITLE
Dynamic ngTable in array

### ISSUE THREAD

**Issue by Andy000** [esvit/ng-table#700]
Hi, I'm facing some issues trying to show multiple ngTable declared into an array.

```javascript
var dataDest = [[]];
$scope.tableParamsDest = [];
$scope.values = [[]];
		
for (var i = 0; i < 4; i++) {
	dataDest[i] = [];

	$scope.tableParamsDest.push(
				new ngTableParams({
				page : 1,
				count : 10, 
				}, {
					total : dataDest[i].length, // length of data
					getData : function($defer, params) {
						$defer.resolve($scope.values[i] = dataDest[i].slice((params.page() - 1)
								* params.count(), params.page()
								* params.count()));
					}
				}));
}
```

As you can see, each ngTable data is bound to dataDest[i]; these are filled later, calling a server routine when the user press on a button. I pass the index of the current table to the function that updates the dataDest[i], so I'm sure I update the right data of the right table, then i call the $scope.tableParamsDest[$index].reload();

The html looks like the following:

```html
<div  ng-repeat="template in templateList" class="container">
  ...
  <table class="table" ng-table="tableParamsDest[$index]">
         <tr ng-repeat="user in $data">
             <td header="'ng-table/headers/checkbox.html'"><input type="checkbox" ng-model="checkboxesDest[$parent.$index].items[$index]"></td>
              <td data-title="'Name'">{{user.name}}</td>
               <td data-title="'Email'">{{user.email}}</td>
	 </tr>
  </table>
  <script type="text/ng-template" id="ng-table/headers/checkbox.html"><input type="checkbox" ng-model="checkboxes.checked" id="select_all" name="filter-checkbox" value="" /></script>              
...                                                              
```

The first time I add items to dataDest[i] and reload the linked ngTable, all works properly. 
If I add some items to another table, dataDest[i] of this table are correctly updated, but after the reload I see within the second table the data added in the first table! 
What could be the problem? Thanks in advance.

**Comment by christianacca** [comment]
Could it be a problem with the closure you've created by `getData` referencing the wrong value for `i`?

**Comment by Andy000** [comment]
Yes! I moved the tables creation in another function which takes an index as parameter and now everything works, thanks Christian. If I am correct, the issue is somehow related to this so question: http://stackoverflow.com/questions/750486/javascript-closure-inside-loops-simple-practical-example

getData, being the inner function, was always bound to the same i value.

**Comment by Andy000** [comment]
Ok, now I have a problem with the following code:
```html
...
  <script type="text/ng-template" id="ng-table/headers/checkbox.html"><input type="checkbox" ng-model="checkboxes.checked" id="select_all" name="filter-checkbox" value="" /></script>              
...                                                              
```
Considering what I wrote in the first post, how could I fix the select all feature?

**Comment by christianacca** [comment]
Maybe this codepen might give you some clues: http://codepen.io/christianacca/pen/MaaoWp

You'll notice more than one table on the page is sharing *the same* header template containing a "select all" checkbox. Each instance of that template ends up referencing a checkboxes object specific to the table where that template is instance is rendered.

**Comment by Andy000** [comment]
Since I had to pass some parameters to the inline template header, so it has to stay within the ng-repeat, I implemented the following code:

```html
<div  ng-repeat="template in templateList" class="container">
  ...
  <table class="table" ng-table="tableParamsDest[$index]">
         <tr ng-repeat="user in $data">
             <td header="'ng-table/headers/checkbox.html'"><input type="checkbox" ng-model="checkboxesDest[$parent.$index].items[$index]"></td>
              <td data-title="'Name'">{{user.name}}</td>
               <td data-title="'Email'">{{user.email}}</td>
	 </tr>
  </table>
  <script type="text/ng-template" id="ng-table/headers/checkbox.html" ng-init="index=$index">
      <input type="checkbox" ng-model="checkboxesDest[index].checked" ng-click="toggleSelectAllDest(index)" class="select_all" value="" />
  </script>           
...                                                              
```
Thanks for the support!

**Comment by christianacca** [comment]
cool glad you found a solution
