### ISSUE TITLE
header-class is not applied to cell in filter row

### ISSUE THREAD

**Issue by alexf2015** [esvit/ng-table#701]
I want to apply a class to an entire column, e.g. hide it with "hidden-xs" or colorize it. Unfortunately the header-class is not applied to the cells in the filter row.

Example: http://codepen.io/anon/pen/YyqKQQ

**Comment by christianacca** [comment]
Ok I can fix that

**Comment by christianacca** [comment]
This is fixed in the latest [1.0.0-beta.5 release](https://github.com/esvit/ng-table/releases/tag/1.0.0-beta.5)
