### ISSUE TITLE
Image lazy-loading supported in row?

### ISSUE THREAD

**Issue by nuxwin** [esvit/ng-table#704]
Hello ;

We are currently using angular-datatables but we are facing many problems with it... THus, we want find another datatable library for angular. Before switching to, we want know if with your datadable system we can have images in rows that are lazy-loaded. For instance, if we get ~300 rows (json data) we want prevent loading of ng-src for rows which are not yet visible. It is possible?

**Comment by christianacca** [comment]
Row visibility is determined by the number of rows you have defined per data page. The default is 10 rows per page. 

You might want to play around with the following examples to get a feel for whether the library is a reasonable fit for your needs:

http://ng-table.com/#/pagination/demo-pager-basic
http://ng-table.com/#/loading/demo-managed-array
http://ng-table.com/#/loading/demo-external-array

**Comment by nuxwin** [comment]
@christianacca 

Thank you for your answer. I tried and all is as expected. Images are loaded only when the rows becomes visible. This is a big difference with angular-datatables (all images are loaded even for the rows that are not showed yet).
