### ISSUE TITLE
The sample on the homepage

### ISSUE THREAD

**Issue by amir-s** [esvit/ng-table#706]
Hello,

I was struggling to make the sample on the homepage work. I ended up reading the source code and understood I need to use `dataset` property instead of `data`.

I mean the sample code here (http://ng-table.com/), step 5. 

Shouldn't it be like this?

```
var self = this;
var data = [{name: "Moroni", age: 50} /*,*/];
self.tableParams = new NgTableParams({}, { dataset: data});
```

**Comment by Nirazul** [comment]
This is not fixed.
And as this was the first address for me to get ng-table to work, it'd be really important to fix this error.

**Comment by tudor2004** [comment]
It seems that the key has changed again. Now it only works with `data` ...

**Comment by PaulMougel** [comment]
Looks like [the CodePen example](http://codepen.io/christianacca/pen/GJeBbo) is using the latest version of `ng-table`. This is the file that is loaded: `https://rawgit.com/esvit/ng-table/master/dist/ng-table.min.js`.

If you're using an older version, for instance the latest tagged version `v1.0.0-alpha.3`, you should use the `data` key, and not `dataset`.

The relevant commit seems to be 380ba21fdf5f4cd69322599a53d86e456851dcea

**Comment by thoughtpalette** [comment]
:+1:  Just spent a couple hours trying to debug why this example wasn't working... Really need to call out that `data` key per version...

Thanks all.
