### ISSUE TITLE
Filter example error

### ISSUE THREAD

**Issue by MrBramme** [esvit/ng-table#710]
There seems to be an issue with the basic filtering example in the dynamicdatacontroller.
Where the cols are defined (this.cols= [...]) for the field age the filter is linked to name and not to age:

Issue
`      { field: "age", title: "Age", filter: { name: "number" }, show: true },`
Solution:
`      { field: "age", title: "Age", filter: { age: "number" }, show: true },`

**Comment by christianacca** [comment]
Fixed and thanks for the spot
