### ISSUE TITLE
Fixed Header (and filters)

### ISSUE THREAD

**Issue by guidospadotto-profesia** [esvit/ng-table#712]
I would like to have a configuration that will make the table header and filters (if any) fixed, whilst the table rows might scroll vertically.
Something similar to this: http://www.bootply.com/JnOYtO9xzn

**Comment by mr-unicoder** [comment]
+1 for that, this is one of the most important features in any real-world grid, i've to say i really lost a client because of that missing feature☺

**Comment by khalla** [comment]
Hi,

I managed to achieve this by using the css in the following jsfiddle:
https://jsfiddle.net/dPixie/byB9d/3/light/

I had to make some minor adjustments both in ng-table dom container and in the css itself.
Good luck

**Comment by anthony-o** [comment]
As said [here](https://github.com/esvit/ng-table/issues/524#issuecomment-218403179), one can be inspired by this [SO question](http://stackoverflow.com/questions/17362077/fixed-header-table-in-angularjs) and perhaps by one of those github projects:

 - https://github.com/alalonde/angular-scrollable-table
 - https://github.com/cornflourblue/angu-fixed-header-table
   - or this fork which seems to be more active: https://github.com/eyeview-opensource/angu-fixed-header-table
 - https://github.com/oci-labs/FixedHeader

**Comment by theaspect** [comment]
See: https://github.com/esvit/ng-table/issues/41#issuecomment-253237169
