### ISSUE TITLE
Update npm with most recent module versions

### ISSUE THREAD

**Issue by dkromp** [esvit/ng-table#731]
The most recent module versions are not downloadable via npm. Please provide them!

**Comment by raphael-boucher** [comment]
+1

**Comment by RobCannon** [comment]
Please add to NPM.  This is last package that I use that I can only get in bower.

**Comment by scatcher** [comment]
+1

**Comment by lennym** [comment]
Can I add some weight to this please? The versions are all there so it's literally a 10 second job to publish.

**Comment by christianacca** [comment]
1.0.0 has been published
