### ISSUE TITLE
Where is documentation for stable 0.8.3?

### ISSUE THREAD

**Issue by lichtner** [esvit/ng-table#734]
I would like to ask, where I can find documentation for 0.8.3, because IMHO http://ng-table.com is generated from last master commit.

And what about release new 1.0.0 stable? Is 1.0.0-beta.8 ready for production? Which version do you recommend me to use now?

**Comment by christianacca** [comment]
You right the doc site is from the latest (beta) version.

I would recommend using the current 1.0.0-beta.8. I've been using in production for a while now.

Make sure you read the migration guide in the repo readme as those changes will be made just before 1.0.0.

The only thing left to do to get to 1.0.0 is adding API documentation.

C

**Comment by lichtner** [comment]
and when you will have time to finish 1.0.0 with API docu? thanks.

**Comment by christianacca** [comment]
I want to say in the next could of weeks but I have a major deadline at work. Realistically it will be Dec now.

**Comment by lichtner** [comment]
ngTable is best angular grid for me
thank a lot
