### ISSUE TITLE
Angular 1.3.x is not support by ngTable 1.0.0

### ISSUE THREAD

**Issue by lichtner** [esvit/ng-table#735]
I was not able to run ngTable 1.0.0 with angular 1.3.x after upgrade  1.4.7 
So I try to fork your basic example and then I only changed angular from 1.4.2 to 1.3.14
and ngTable doesn't work... Only 1.4 will be supported?

http://codepen.io/anon/pen/WQgEQE?editors=101

**Comment by lichtner** [comment]
I have no problem with this, I upgraded my project. May be you can add info about required version of angular in README.md

**Comment by zygmcc** [comment]
i can't use this with angular 1.4.6
