### ISSUE TITLE
1.0.0 Stable version ? + Custom Filter + TypeScript Definition

### ISSUE THREAD

**Issue by okamiconcept** [esvit/ng-table#736]
Hello, first of all thank you for all the good work ! :)

On your main page of GitHub you say "The 1.0.0 release is expected to land in 2-3 weeks", but it seems the beta version last more than that ;)

I really want to use the 1.0.0 version in my projects but i use bower and it recommands only stable version (currently 0.8.3).

Have you an idea for the date of the first release of 1.0.0 ? I want to use it for my next big project but it's difficult because we have no precise roadmap here ...

Can you help us a little on that ? :)

Futhermore i work on a custom filter plugged in ngtable which could reproduce the kendo ui filter but more powerful 
![ngtable-customfilter](https://cloud.githubusercontent.com/assets/14908721/10966574/b5fea54a-83b4-11e5-92dd-ddf88d957618.png)

If you interested i can share my work.

I've also implemented TypeScript definition for 0.8.3 version, it's not complete but it works well, it could help someone to have a real TSD on DefinitelyTyped.

```typescript
declare module "ng-table" {
    var _: string;
    export = _;
}

declare module angular.ngtable {

    interface ITableParams {
        new (baseParameters: IParams, baseSettings: ISettings): ITableParams;
        data: any;
        parameters(newParameters?: string, parseParamsFromUrl?: string): IParams;
        settings(newSettings?: string): ISettings;
        page(page: number): IParams;
        page(): number;
        total(total: number): ISettings;
        total(): number;
        count(count: number): IParams;
        count(): number;
        filter(filter: { [key: string]: string }): IParams;
        filter(): any;
        sorting(sorting?: string | Array<string>): IParams;
        sorting(): { [key: string]: string };
        isSortBy(field: string, direction: string): boolean;
        orderBy(): Array<string>;
        getData(params: ITableParams): ng.IPromise<any>;
        getGroups(column: number | Function): ng.IPromise<any>
        generatePagesArray(currentPage: boolean, totalItems: boolean, pageSize: boolean): Array<IPage>;
        url(asString?: boolean): Array<string> | any;
        reload(): ng.IPromise<any>;
        reloadPages(): void;
    }

    interface IPage {
        type: string;
        number: number;
        active: boolean;
        current: boolean;
    }

    interface IParams {
        page?: number;
        count?: number;
        filter?: { [key: string]: string };
        sorting?: { [key: string]: string };
        group?: { [key: string]: string };
        groupBy?: { [key: string]: string };
    }

    interface ISettings {
        $scope?: ng.IScope;
        $loading?: boolean;
        data?: any;
        total?: number;
        defaultSort?: string;
        filterDelay?: number;
        counts?: Array<number>;
        sortingIndicator?: string;
        getGroups? (column: number | Function): ng.IPromise<any>;
        getData? (params: ITableParams): ng.IPromise<any>;
        debugMode?: boolean;
    }

    interface IFilterConfigProvider {
        setConfig? (customConfig: IFilterConfig): void;
        resetConfig? (): void;
    }

    interface IFilterConfig {
        defaultBaseUrl?: string;
        defaultExt?: string;
        aliasUrls?: { [key: string]: string }
    }

    interface IDefaults {
        params: IParams;
        settings: ISettings;
    }
}
```

**Comment by christianacca** [comment]
That filter looks very nice. And yes I think me and everyone else would find it useful if you shared :-)

So you noticed that 1.0.0 release date has slipped a bit!

Usual problem - major deadline so already working weekends :-(

I would say that the API is stable now as long as you aren't using anything in the depreciated section of the repo readme.

The only main thing left to do is to document the API. This is partly done already. If you run gulp for the repo a API doc site is generated from the jsdoc comments from the code.

The jsdocs need quite a bit of improvement to make this generated site useful.

Once this is done then the project will be good for 1.0.0.

So I would say that to create a quality typed definition you will need the API doc site generated. I would like to say I can do this in the next week or two, but the way work is its more likely going to happen in Dec.

C

**Comment by okamiconcept** [comment]
Ok Christian, thanks for your answer !

I understand the problematics of work deadlines, for me i am in a R&D part in my work so i use that to improve some angularjs modules.

I will work on an extension for ngtable to expose my custom filter, i will keep you in touch when a first version is ready.

Keep the good work ! I will wait for the 1.0.0 release !

Max
