### ISSUE TITLE
Support nested objects for grouping tables

### ISSUE THREAD

**Issue by lichtner** [esvit/ng-table#742]
Grouping tables with ngTable works with flat dataset like this:

```
usersWithArticles = [
{user: 'aaa', articleTitle: 'article a1', articleContent: '....'},
{user: 'aaa', articleTitle: 'article a2', articleContent: '....'},
{user: 'bbb', articleTitle: 'article b1', articleContent: '....'}
...
];
```
and ngTable rebuild list to nested form with attributes `data` and `value`.
IMHO nested json objects is more natural in js something like:

```
usersWithArticles = [
{user: 'aaa', articles: [
    {title: 'article a1', content: '....'},
    {title: 'article a2', content: '....'}
]},
{user: 'bbb', articles: [
    {title: 'article b1', content: '....'}
]}
...
];
```
Why did you choose first flat way? Second type of nested objects will be supported? I thing nested object for group list will be very useful for many developers.

**Comment by lichtner** [comment]
Now I tried to hack it:
```html
<tr ng-repeat-start="group in $groups" class="ng-table-group">
    <td>{{group.data[0].user}}</td>
</tr>
<tr ng-repeat="article in group.data[0].articles" ng-repeat-end>
    <td>{{article.title}}</td>
</tr>
```
it works but it is tricky ;-) 

So same question: Do you have plan support nested objects? I know for nested objects is impossible to change grouping column, but for me it is not important.

**Comment by christianacca** [comment]
I tend to create nested ng-table's for the nested objects that you describe. EG:

![image](https://cloud.githubusercontent.com/assets/886590/11141268/9adc82d2-89db-11e5-803d-8d2391722796.png)

**Comment by christianacca** [comment]
Here's the typical html markup to define such nesting:

```html
<table ng-table="ctrl.tableParams">
    <tr ng-repeat-start="row in $data">
        <!-- td's -->
        <td>
            <!-- toggle row selection -->
        </td>
    </tr>
    <tr ng-repeat-end
        ng-if="row.isSelected" ng-controller="childrenController as items">
        <td colspan="4" style="padding-left: 20px">
            <table ng-table="items.tableParams">
                <tr ng-repeat="item in $data">
                    <!-- td's -->
                </tr>
            </table>
        </td>
    </tr>
</table>
```

**Comment by lichtner** [comment]
perfect, thanks a lot. is it possible to use it now?

**Comment by christianacca** [comment]
Yes. I've been using this approach since an around v0.5

**Comment by christianacca** [comment]
BTW, the grid you saw in the screen shot had custom css styles. In other words there are no styles from ng-table specific to nesting tables.
