### ISSUE TITLE
Replacing data in 1.0.0

### ISSUE THREAD

**Issue by SNTRwa** [esvit/ng-table#743]
I can't figure out how to replace data in table in 1.0.0 version. For now my working version looks like that, it's filled with data initially but new data is getting ignored.
```
var self = this;
self.tableParams = new NgTableParams({
    sorting: {
      like_count: "desc"
    }
});
```
then some function to get data from http: 
```
var getData = function(parameters){
$someHttpRequest(parameters).then(function(response){
    self.tableParams.settings({
        dataset: response.data
      });
}
```
I tried to use getData in tableParams.settings but outcome was basically the same. I just want to fire getData() with different parameters and obtain new data in table. Any hints?

**Comment by christianacca** [comment]
`self.tableParams.reload()`

**Comment by SNTRwa** [comment]
unfortunately that doesn't work either.
There is any other way?

**Comment by essuraj** [comment]
that doesn't work either.
