### ISSUE TITLE
is there a trick to using .reload() in an interval function?

### ISSUE THREAD

**Issue by dkromp** [esvit/ng-table#745]
Is there a trick to using .reload() in an interval function? I have a table with filterable, sortable columns, and a getdata function in the table's settings parameter that loads the filtered parameters in the url. I put in some console.log('interval fired') in the interval function and a console.log('finished') at the end of the getdata function. I noticed the reload in the interval function seems to be getting called twice. I also notice that the url loads parameters inconsistently.

If I manually call a .reload() of my ng-table from a ng-click function, there are no problems. This makes me think there's a problem running the .reload from an interval as it might interfere with the digest cycle... I don't have much visibility into the problem.

I saw this post, https://github.com/esvit/ng-table/issues/473, but I didn't get much from the responses.

    $interval(function() {
        vm.depotTable.reload();
    }, 5000);

I am using the following versions: ng-table: 0.8.3 and angular: 1.4.7.

**Comment by christianacca** [comment]
What version of ngTable are you using?

**Comment by dkromp** [comment]
0.8.3

**Comment by dkromp** [comment]
The trick here wasn't much of a trick -- just had to cancel the interval.

            vm.refreshData = $interval(function(){
              vm.depotTable.reload();
            }, 3000);
            
            $scope.$on("$destroy",function(){
                  if (angular.isDefined(vm.refreshData)) {
                      $interval.cancel(vm.refreshData);
                  }
            });

**Comment by mathieug** [comment]
Thanks @dkromp :+1:
