### ISSUE TITLE
[Question] What's the proper way to set column widths

### ISSUE THREAD

**Issue by arvenil** [esvit/ng-table#75]
Hi

What's the proper way to set column widths? How can I for example pass `class="span1"` to `<th>` elements?

**Comment by minohimself** [comment]
Hi Guys, is it still possible to set the column width ? i dont see any resource leading to how to do that

**Comment by AlexLai1990** [comment]
http://stackoverflow.com/a/33232121 this works for me. Just separate <thead> from <tbody> and without using "data-title".
