### ISSUE TITLE
 give a wrapper for the table element [request]

### ISSUE THREAD

**Issue by fish520** [esvit/ng-table#757]
In my case, I have to put a grid at a certain position, with scrollable action if it overflowed. but the pagination should be kept in sight, so I'm thinking to add a `overflow: auto` css rule to the parent element of the `<table>`, so the pagination would be able to stay fixed right beneath the wrapper if it was added `position: fixed`.
namely, from
```html
<div class="wrapper">
     <table>....</table>
    <pagination></pagination>
</div>
```
to
```html
<style>
// overwrite
.table-wrapper {
      height: 200px;
      overflow: auto;
}
pagination {
     position: fixed;
}

<div class="wrapper">
     <div class="table-wrapper">
          <table>...</table>
     </div>
          <pagination></pagination>
</div>
```

**Comment by hxlniada** [comment]
+1

**Comment by hxlniada** [comment]
Is there anyone out there?

**Comment by esvit** [comment]
The best solution for this issue is create directive:

```js
function () {
  return {
    priority: 1002,
    link: function (scope, element, attributes, ngModel) {
      element.wrap('<div class="table-wrapper"></div>')
    }
  };
}
```

and add it to you table

**Comment by fish520** [comment]
good solution, thanks and I'll have a try.
