### ISSUE TITLE
Some clarifications

### ISSUE THREAD

**Issue by AmitMY** [esvit/ng-table#759]
I am expending the dynamic Ng-Table to have more features, but first, I need to know if it already has some of these features which I could not find online:
- Columns pining (Have x columns pinned to the left, and all of the other table columns will be horizontally scroll-able).
- Columns fixed width - is there an attribute in the columns array (like width: 50)
- Fixed header - when you scroll the table, the header floats above the table so you can see it all the time.
- Row selection / Multiple rows selection (check box, click, and ctrl+click)
- A general filter - one text box that filters the entire table
- Custom filters - have templates for custom filters (I want to call an async request to get data for the filter from the server. Example: languages)
- Horizontal/Vertical scrolling for the table

And a problem I encountered:
When I have a filter type "number", when I put like "3" in it, and then delete it (now the filter contains: ""), it filters for 0. I know why this happens, but is there a fix for it? (Without removing the ability to filter for 0)

These are just part of the planned features, because all the others are pretty individual / have been done.

PS:
Of course when I finish this entire thing goes public here!

**Comment by christianacca** [comment]
The `number` filter sounds like a pain. I've had similar problems when creating a custom boolean filter.

There are a few possible solutions that come to mind:

* enhance [ngTableDefaultGetData#applyFilter](https://github.com/esvit/ng-table/blob/master/src/scripts/ngTableDefaultGetData.js) to remove empty strings just before the filter is applied to locally managed data
   * this is not universally applicable, the behaviour could be made an option of [ngTableFilterConfig](https://github.com/esvit/ng-table/blob/master/src/scripts/ngTableFilterConfig.js)
* extend the `number` template with the behaviour itself to strip away the empty string
* modify [ngTableParams#filter](https://github.com/esvit/ng-table/blob/master/src/scripts/ngTableParams.js) to remove empty strings (optionally make configurable as above)

As to the features in your list:

* Columns pining - not implemented
* Columns fixed width - already easy for your own html to include a `colgroup` tag which already has access to your list of columns. Remember, your column definition can have any fields it wants, one of which could be a width
* Fixed header - not implemented
* Row selection / Multiple rows selection - that's easy to add for when the ng-table is managing a `dataset` in memory, but get's surprisingly complicated to implement in practice when the data is on the server.
    * I've implemented this feature to work with both local and server-side data as an extension (closed source), maybe I can get my employer to agree to open source it
* A general filter - see http://ng-table.com/#/filtering/demo-api
* Custom filters - see http://ng-table.com/#/filtering/demo-custom-template
* Horizontal/Vertical scrolling - not implemented, but then I'm guessing that an app could use it's own custom css (?)

**Comment by AmitMY** [comment]
That was a very informative answer!
I did not reply sooner because I wanted to try anything you said before.
Almost everything was a success (including multiselect rows)

The only things I have yet tried are using the server to refresh the list every orderBy and every filter change, but that is easy.

The only two thing I did not manage to do (and did try) are pinned columns and a fixed header.
Do you have any idea how to implement it?

** I have absolutly no Idea how to expend a library, so I created all of the features around the table, with settings for everything

This is the current situation: [Image](https://i.gyazo.com/0afa61457174134e0f507b1219374013.png)
(I also created a CSV export, but I dont know how to add it to the library to send a codepen like requested in ng-table.com)

**Comment by alex3stones** [comment]
hi, AmitMY , very glad to hear you have already created a csv export, which is I am looking for. can you share the code here? it can export the entire data set after filtered? thx

**Comment by AmitMY** [comment]
I did not do it like that, I can add it (very simply, but only tomorrow (I dont have remote access to work)).
My export is dependent on rows selection. yes, you can "select all" and then export, but that is just not a good answer.
Do you still want me to send it to you?
*after creating the export, I found that there is this: https://github.com/esvit/ng-table-export - which I did not really looked into, but maybe it can help
