### ISSUE TITLE
$ isn't searching in all columns

### ISSUE THREAD

**Issue by feniixx** [esvit/ng-table#766]
I want to make a global filter, I mean, an input where the user can search by all fields, but using `$` isn't working:

This is the `ng-change` binded function:

``` js
        function tableFilter( stringToSearch ) {
            vm.table_data.filter( { $: stringToSearch } );
        }
```

If I specify a column like `name` instead of `$` it works... Also I don't understand why at the examples you use `dataset` and it works, but when I tried with it, it didn't work, then I changed it to `data` and it works, I'm talking about the second json of `NgTableParams`.

**Comment by AmitMY** [comment]
You can try - vm.table_data.filter()['$'] = stringToSearch;
I belive this is the setup that works for me

**Comment by jyoona** [comment]
If AmitMY's method didn't work, try vm.data_table.reload() after.
That worked for me
