### ISSUE TITLE
Is there any solution to get the dataset after filter?

### ISSUE THREAD

**Issue by alex3stones** [esvit/ng-table#771]
once I click a 'filter' button, how can I get the total dataset?

**Comment by AmitMY** [comment]
tableSetting's $data parameter is the filtered data set.

**Comment by alex3stones** [comment]
self.tableParams.filter({ $: term });
      self.tableParams.reload();
      $scope.getArray = self.tableParams.data;

here, self.tableParams.data is only the 1 page data set, how can I get the full data?

**Comment by AmitMY** [comment]
As far as I know, you cant because of the pagination function at the end of getData.

You can create your own getData, that before cutting the array, just saves the new array in a local location.

**Comment by alex3stones** [comment]
My problem is that I don't know how to create my getData function cause of newbie for Angularjs, can u (anyone else) plz help me? thanks in advance.

**Comment by AmitMY** [comment]
Oh that is pretty easy using angular $filter
This is the code; http://codepen.io/anon/pen/adNyyd?editors=001
Now, if you want to save the data to a local variable before cutting to pages.
(var myData = orderedData) before the slicing.

**Comment by christianacca** [comment]
This is now supported as per https://github.com/esvit/ng-table/pull/937
