### ISSUE TITLE
When will 1.0.0 production be available?

### ISSUE THREAD

**Issue by pshivale** [esvit/ng-table#792]
1.0.0 beta going on for a while. When will 1.0.0 production be available?

**Comment by christianacca** [comment]
Yeah that's my bad.

Over the recent break I completed the last major remaining tasks - document the API by creating a type definition.

I'm now trying to find some time to remove the depreciated parts of the API (see readme), to add a link to the type definition from the docs site and then push to npm, etc.

I do have hopes that this will be done the next couple of weeks.

C

**Comment by pshivale** [comment]
Thanks C! Looking forward to it.
Lot of examples (e.g. dynamic grouping) have features from beta and we cannot use beta release in production environment.

**Comment by kambalin** [comment]
Hi, please update docs (or correct me), but filterDelay does not work any more in 1.0.0b9. Instead of filterDelay I'm using filterOptions: { filterDelay: xxxx }.

**Comment by ccrowhurstram** [comment]
So just an update. The [typings](https://github.com/typings/typings) project changes the way type definitions are delivered.

I want ensure that I understand this and how it relates to packaging using npm.

When is it going to be ready? I'm trying to learn rxjs and angular 2 and that's taking a big chunk of my time. Therefore I don't want to say when as I have failed to deliver on any dates thus far.

On a positive note, I do have plans to try and upgrade ng-table to angular2 and rxjs (where appropriate). To be fair this is more for my benefit to learn new concepts on a real project. I guess others who are using ng-table might also benefit...

**Comment by loxiw** [comment]
But ngTable will keep working with AngularJS, right?

**Comment by ccrowhurstram** [comment]
Yeah there will be a legacy branch for ng-table that will be created. This will enable the community to maintain the angular 1 version of ng-table in parallel with an angular 2 version.

**Comment by christianacca** [comment]
1.0.0 has been published
