### ISSUE TITLE
ng-table css 0.8.3 installed with bower does not provide sorting arrows

### ISSUE THREAD

**Issue by casper1149** [esvit/ng-table#797]
Hi,

I have noticed that if I use bower installed ng-table css, I do not see sorting arrows, however if I specify
https://cdnjs.cloudflare.com/ajax/libs/ng-table/0.8.3/ng-table.css
arrows are there

**Comment by anuja-joshi** [comment]
@casper1149 I have installed ng-table 0.8.3 through bower, but did not come across such issue. Please make sure that you are properly including css file.

**Comment by christianacca** [comment]
Also bower is no longer supported as of the latest version of ng-table
