### ISSUE TITLE
Is it possible to define a per column custom filter?

### ISSUE THREAD

**Issue by cybercyst** [esvit/ng-table#799]
For example, if I wanted to have custom filter to search for dates within a specific range on column 'a',
then wanted to search for sub strings in column 'b', but exact matches in column 'c'...

I keep reading over the documentation and code for a scenario like this, but can't find one...

**Comment by SpoinkyNL** [comment]
Try something like this

```javascript
tableParams = new NgTableParams({}, {filterOptions: { filterFn: columnSpecificFilter }});
        
function columnSpecificFilter(data, filterValues) {
    if (filterValues.columnA != null) {
        data = customFilter(data);
    };

    // Remove columnA since it was filtered already
    delete filterValues.columnA;
    data = $filter("filter")(data, filterValues);

    return data;
}
```

**Comment by cybercyst** [comment]
@SpoinkyNL That worked... I missed the filterFn, not filterComparator! 

Thanks for your help!
