### ISSUE TITLE
Bootstrap 4

### ISSUE THREAD

**Issue by NoZiL** [esvit/ng-table#840]
Pagination style doesn't work with BS4 and also sorting icons

**Comment by jrbotros** [comment]
I've put in a fix for the pagination in #923 (not sure which sorting icons you're talking about).

In the meantime, you can watch for changes in your link function:
```
    link: function (scope, elem) {
      // Remove if https://github.com/esvit/ng-table/pull/923 is merged
      scope.$watch(
        () => elem.find('.pagination'),
        (now, before) => {
          now.find('li').addClass('page-item')
          .find('a').addClass('page-link')
        }
      )
    }
```

**Comment by jrbotros** [comment]
I've put in fix #923 for the pagination styling (not sure which sorting icons you're referring to).

In the meantime, you can import the Bootstrap pagination files with sass:
`@import 'bootstrap/scss/pagination';
 
and then extend the from relevant classes:
```
  .pagination {
    li {
      @extend .page-item;
      a {
        @extend .page-link;
      }
    }
  }
```

**Comment by christianacca** [comment]
PR merged

**Comment by christianacca** [comment]
... and now published to npm as version 2.1.0

**Comment by mborkland-usf** [comment]
It still does not work with Bootstrap 4.

**Comment by Xsmael** [comment]
Pagination doesnt work with BS4 indeed.
