### ISSUE TITLE
Latest stable version is 0.8.3 but docs on master are for unstable v1.

### ISSUE THREAD

**Issue by jtschoonhoven** [esvit/ng-table#841]
We're on v0.8.3, planning to have a number of engineers ramp up on ng-table quickly. It's confusing that the docs on master are for an unstable version with many breaking changes from stable. Our plan is to just fork the repo and DIY our own docs, but...

**Questions**

How unstable is v1? Should we just upgrade?

If I created a PR to point the master README at the 0.8.3 version of the API would it be accepted? I could add some bonus details as well.

cc @ccrowhurstram

**Comment by jtschoonhoven** [comment]
ping @ccrowhurstram @esvit
If this repo is no longer maintained, could we add a deprecation notice?

**Comment by jtschoonhoven** [comment]
Ended up forking the repo for ourselves. You can find it here https://github.com/lyft/ng-table

**Comment by christianacca** [comment]
This repo and npm is now updated to 1.0.0 which is the current stable release
