### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by thiagoaraujo84** [esvit/ng-table#849]
The getting started process decribed in http://ng-table.com/#/ does not work.

The endpoint https://cdn.rawgit.com/esvit/ng-table/v1.0.0/dist/ng-table.js responses with 404 error.

I also tried use the command "bower install ng-table", but the examples does not work with this version.

I only get my project working cloning the dist folder of github project.

**Comment by dlinx** [comment]
Already fixed, Please close this issue.

**Comment by thiagoaraujo84** [comment]
Thanks!
