### ISSUE TITLE
Filtering data from server REST call. Tutorial issue.

### ISSUE THREAD

**Issue by pietro-fragnito** [esvit/ng-table#851]
Dear all,

I have not clear how to perform filtering when catching data from server.

The tutorial says: 

> Got a getData function?
> In this case you'll need to apply the values from NgTableParams.filters() to the data you want to display in your table. This is typically the case when the data is being fetched from the server

But there isn't (or I haven't found it) that tutorial: can you help me? I correctly visualize the data coming from the REST call, but filtering (and pagination) doesn't work.

In any case the issue is that the tutorial is incomplete or not helping for this case.

Thanks a lot.

**Comment by PeterRangelov** [comment]
I'm unclear on this as well. @pietro-fragnito can you share a resolution?
