### ISSUE TITLE
Your continuous integration tests fail even on readme.md!

### ISSUE THREAD

**Issue by stimg** [esvit/ng-table#856]
One of two tests last time is always fail: 
`ci/circleci — Your tests failed on CircleCI` 
...even if someone makes changes in `readme.md`. I've checked at least last three failed pool requests and there is always the same error at `$ npm test`:
```
INFO [karma]: Karma v0.12.37 server started at http://localhost:9876/
INFO [launcher]: Starting browser Chrome
INFO [Chrome 43.0.2357 (Linux 0.0.0)]: Connected on socket f0T0JpKMMEQYDM9GqB-A with id 95284439
Chrome 43.0.2357 (Linux 0.0.0) ERROR
  Uncaught TypeError: Cannot read property 'module' of null      <--------------------
  at /home/ubuntu/ng-table/dist/ng-table.js:28


npm ERR! Test failed.  See above for more details.
```
dist/ng-table.js:28 --->  `angular.module('ngTable', []);`

**Comment by christianacca** [comment]
That's [fixed](https://circleci.com/gh/esvit/ng-table/228) now thanks to @astik
