### ISSUE TITLE
Batarang hints

### ISSUE THREAD

**Issue by AmitMY** [esvit/ng-table#857]
Angular 1 has a coding style, in which they state the names styles. Batarang hints which names are not fitting the style, please consider changing it.

> Consider renaming ngTableFilterRowController to NgTableFilterRowController.
> Consider renaming ngTableSorterRowController to NgTableSorterRowController.
> Consider renaming ngTableController to NgTableController.
>

**Comment by christianacca** [comment]
That should happen when the JS is ported to typescript as these controllers will become classes
