### ISSUE TITLE
Gulp or Grunt ?

### ISSUE THREAD

**Issue by astik** [esvit/ng-table#860]
Is there a reason why there is both mechanism in this project ?
It would be clearer to only have one of them.
Maybe gulp as it is faster ?

**Comment by christianacca** [comment]
That's my fault. I used gulp to auto-generate API documentation for ng-table.

There was a plugin for gulp but not grunt.

My preference is gulp, but I don't want to spend time refactoring the build over to gulp (unless at some point it becomes easier)

**Comment by christianacca** [comment]
FYI, I'm going to be moving the build over to webpack soon so both gulp and grunt will both be removed...
