### ISSUE TITLE
Gouping renders empty table Angular 1.5.6 and ng-table 0.8.3

### ISSUE THREAD

**Issue by sicollins** [esvit/ng-table#863]
I have project using latest Angular 1.5.6. The latest ng-table I get when doing bower install (this is in VS 2015 Update 2) based on this is 0.8.3 (even though the example on your site all use 1.0.0-beta.9??)

Using your js and html from the example http://ng-table.com/#/grouping/demo-grouping-basic

Does not work. When I inspect <tbody> there is nothing inside the ng-repeat so no data row are rendered.

If I upgrade my bower package manually (not using bower package manager in VS) and use 1.0.0-beat.9 it works and I get my grouped data.

**Comment by christianacca** [comment]
I would suggest upgrading to 1.0.0-beta.9 - it's stable and the recommended version

**Comment by razazaidisd** [comment]
Its giving me 0.8.3 version while installing with bower.

**Comment by christianacca** [comment]
Try:
```cmd
bower install ng-table#1.0.0-beta.9 --save
```
