### ISSUE TITLE
unclear what vhave changed between 0.9 and 1.0 

### ISSUE THREAD

**Issue by marcelloh** [esvit/ng-table#867]
All the examples on the ng-table.com also still work with the 0.9.
All my apps broke because of 1.0 so I "stole" the old 0.9 from the website and made that my local version.
Now it all works again.
:-(

**Comment by christianacca** [comment]
[CHANGELOG.md](CHANGELOG.md) documents all the releases and what changed in each release (including the breaking changes).

Also, there is a guide for [upgrading from earlier versions](https://github.com/esvit/ng-table#upgrading-from-an-earlier-version) that might help you.

**Comment by marcelloh** [comment]
I thought I had changed all NgTableParams, but one was left behind. Anyway; thanks for the answer.
