### ISSUE TITLE
Problems with NPM

### ISSUE THREAD

**Issue by AmitMY** [esvit/ng-table#871]
I have two questions:
Why does:
`npm install --save ng-table@1.0.0-beta.9` fails, saying there is no such version?

Also, I looked at your package, and it looks like gulp is a dependency, not a dev dependency, Why is that?

**Comment by christianacca** [comment]
version 1.0.0-beta.9 was only published to bower and not npm.

To see the all the published versions on npm:

npm info ng-table versions

package.json as far as I can tell declares gulp as a dev dependency (see
https://github.com/esvit/ng-table/blob/cf8bf8ad2c871ff8b939756857fa4b376f1c0ba4/package.json#L31
)

**Comment by BrendanDougan** [comment]
Any plans to publish 1.0.0 on npm? I've just spent a few hours trying to figure out why my code isn't working to discover the documentation refers to  1.0.0 and I'm working with 0.8.3

**Comment by christianacca** [comment]
``cmd
npm install ng-table --save
```

That should be installing 1.0.0, at least it does on my machine.

**Comment by BrendanDougan** [comment]
Working for me now too, thanks for your help!
