### ISSUE TITLE
Error in ng-table.min.js

### ISSUE THREAD

**Issue by sidh447** [esvit/ng-table#873]
I am getting error in ng-table.min.js in the first line itself

`Syntax error on tokens, they can be merge to form !`

![ng-table min](https://cloud.githubusercontent.com/assets/19812928/16339665/7eda8874-3a41-11e6-9514-0f4b5c174722.PNG)

**Comment by ccrowhurstram** [comment]
The `grunt-contrib-uglify` plugin is generating this file. 

The script does still work - at least all the examples in the http://ng-table.com are using this script.
