### ISSUE TITLE
v0.8.3 dependencies should be dev dependencies

### ISSUE THREAD

**Issue by jnu** [esvit/ng-table#880]
ng-table v0.8.3 broke a build in a CI environment. npm had a problem installing dependencies (`dgeni`). I noticed that in the v1.0.0 alphas all of these dependencies have been moved to `devDependencies`, so I [patched `v0.8.3` to do the same](https://github.com/jnu/ng-table/commit/b0f7ce20492d96f46687f154cbb195d90beb0021), which fixed the issue.

Could you release a `v0.8.4` with this change? I'd prefer to install from the npm registry rather than my gh fork.

Thanks!

**Comment by christianacca** [comment]
Sorry but I don't have the time to patch old versions of ng-table and then publish these on npm.

Best bet is to upgrade to the 1.0.0+
