### ISSUE TITLE
Select filter is showing all values as undefined

### ISSUE THREAD

**Issue by raul1991** [esvit/ng-table#890]
My html 

> `<table ng-show="!loading" show-filter="true" class="ebTable eftf ebTable_striped" ng-table="tableParams" template-pagination="custom-pager">
>         <tr ng-repeat="probe in $data">
>             <td data-title="'Host'" sortable="'host'" filter="{host: 'select'}" filter-data="fetchHosts($column)">{{probe.host}}</td>`

My controller

> `$scope.fetchHosts = function ($column) {
>         if($column.title() === "Host") {
>             return [{host: "192.168.1.34"}, {host: "192.168.1.36"}];
>         }
>     };`
> 

The documentation for the select filter only says that the fetchData function must return an array or a promise that returns an array etc. Despite that it fails, something is missing from the documentation i think.

**Comment by raul1991** [comment]
Ok, i have got it working. The values are being shown in the dropdown now(not undefined anymore). The doc did not specify that the id and title attribute are necessary. I wish the document was more explicit. Please correct me if i am wrong in using id and title. How can i help improve the documentation ?

**Comment by harihar** [comment]
@raul1991 Can you please close this since you have solved already?

**Comment by aldo-o** [comment]
Thank you. The reason why I barely use ngTable, it's because of documentation.

**Comment by gpiancastelli** [comment]
This should be reopened until the documentation is fixed. Searching Google for an explanation of the "undefined" behaviour and being pointed to a closed issue does not really "solve" the problem, you know.

**Comment by raul1991** [comment]
I agree. Just in case you could not get it done. Make sure to pass 'id' and title for a drop-down.

**Comment by worthy7** [comment]
Can't you just fix the docs yourself and submit a pull request....
