### ISSUE TITLE
How to create a search filter on all columns?

### ISSUE THREAD

**Issue by raz3r** [esvit/ng-table#897]
Hi, I am trying to create a search filter that acts on all columns, not just one. Something similar to the search box of Datatables. I couldn't find anything in the documentation even though other issues suggest the use of $ wildcard but I am not sure how to implement that.

Thank you.

**Comment by raz3r** [comment]
Nevermind, found a way :)

**Comment by sevmardi** [comment]
@raz3r Would you contribute your thoughts or ideas so the rest of us might find this helpful? Thanks a lot.
