### ISSUE TITLE
checkbox in header

### ISSUE THREAD

**Issue by ciccio86** [esvit/ng-table#9]
Is there a way to manually put a checkbox in the header of the table?

**Comment by kobi-leverate** [comment]
Check out this answer: http://stackoverflow.com/a/31065684/133665

**Comment by ashishnaghate** [comment]
Use ng-table to perform this task. The code given below:
1. Add the script to to create the template for checkboxheader.
`<script type="text/ng-template" id="checkboxheader.html">
                    <div class="checker">
                        <span ng-class="{'checked': Allchecked}"><input class="icheck black " type="checkbox" ng-model="Allchecked" ng-click="checkall($data, Allchecked)" ng-checked="allchk"></span>
                    </div>
                </script>`
2. In first td of ng-repeat add following code.
````
<td data-header="'checkboxheader.html'">
       <div class="checker">
           <span ng-class="{'checked': check[$index] == eventList.id}">
              <input ng-model="check[$index]" ng-click="   singlecheck(eventList.id, check[$index], $index)" ng-checked="check[$index] == eventList.id" type="checkbox" value="1" name="id[]">
            </span>
       </div>
</td>
````
