### ISSUE TITLE
Missing Bootstrap dependency

### ISSUE THREAD

**Issue by djpcoc** [esvit/ng-table#901]
A Bootstrap pagination tag is used in line 9 of src/browser/pager.html.

` <ul ng-if="pages.length" class="pagination ng-table-pagination">`

Yet no Bootstrap dependency is declared in bower.json which results in Bootstrap being loaded in after ng-table. The following code then has no affect as it is overwritten by Bootstrap styling.

`.ng-table-pagination {
  margin-top: 0;
}`

**Comment by christianacca** [comment]
I'm on the fence as to whether bootstrap should be included as a dependency.

The only dependency that ng-table has is on bootstrap styles. Including a dependency on the full bootstrap package seems the wrong thing to do.

One option would be to include a dependency on [bootstrap-css-only](https://github.com/fyockm/bootstrap-css-only) package. But then what about those apps that want to use [bootstrap-sass](https://github.com/twbs/bootstrap-sass) - ng-table has "forced" an unwanted dependency on the app.

So I don't think there is necessarily a right solution for the current feature set of package managers.

**Comment by christianacca** [comment]
Oh, and also a reminder bower is no longer supported by ng-table
