### ISSUE TITLE
Bazalt-cms page hijacked

### ISSUE THREAD

**Issue by CodyMorris** [esvit/ng-table#913]
Hello,

I wanted to warn you that multiple links on your readme direct to a page being rerouted + serving adware/malware.

This includes the Bazalt CMS link at the bottom of your page (http://bazalt-cms.com/) and anything sourced from there (example: the Export to CSV example page)

**Comment by christianacca** [comment]
Thanks @CodyMorris for the "heads up".

Actually, that that bit of advertising on the site is from the owner of this repo so it's "OK"
