### ISSUE TITLE
Installation require a peer of angular 1.2

### ISSUE THREAD

**Issue by jesmarquez** [esvit/ng-table#918]
This error show installing ng-table:

npm install ng-table --save
meanjs@0.5.0-beta D:\jamarquez\comovalatest
+-- UNMET PEER DEPENDENCY angular@^1.2
+-- UNMET PEER DEPENDENCY eslint-plugin-react@^4.0.0
`-- ng-table@1.0.0

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm WARN eslint-config-airbnb@6.0.2 requires a peer of eslint-plugin-react@^4.0.0 but none was installed.
npm WARN grunt-istanbul@0.6.2 requires a peer of grunt@~0.4.5 but none was installed.
npm WARN ng-table@1.0.0 requires a peer of angular@^1.2 but none was installed.

My enviroment:
Windows 7
npm 3.10.6
node 4.5.0

Any help,

**Comment by christianacca** [comment]
Yes this is by design.

It follows the same pattern as angular itself (as of angular 2). 

For more information see [official angular guide](https://angular.io/docs/ts/latest/guide/npm-packages.html#!#why-peer-dependencies).

**Comment by gmeena** [comment]
how to solve the problem then?
