### ISSUE TITLE
wrong sample in website

### ISSUE THREAD

**Issue by getJv** [esvit/ng-table#920]
Helooo guys,

Just for checking, I think that step number 5 in website (http://ng-table.com/) sample it is incomple.

The step 5 says:

`In your javascript file within the controller where you plan to use ng-table, declare:
var self = this;
var data = [{name: "Moroni", age: 50} /*,*/];
self.tableParams = new NgTableParams({}, { dataset: data});`

But in our controller we need to inform the param: 'NgTableParams', other wise we will receive: a error message, becouse NgTableParams it is undefined.

My sample:
app.controller('certCtrl',['$http','NgTableParams',function($http,NgTableParams) ...

Bye!!!

**Comment by christianacca** [comment]
Hi @getJv,

You're right of course. However, I think adding the `NgTableParams` as an injectable to your controller is going to be obvious (hopefully!) and therefore doesn't need to mentioned.
