### ISSUE TITLE
Bower dist folder missing

### ISSUE THREAD

**Issue by Nighthawk22** [esvit/ng-table#925]
When i do a clean install in bower, the dist folder is missing.
Am I misunderstanding something?
![ng-table](https://cloud.githubusercontent.com/assets/11962722/19265937/ac92c284-8fa7-11e6-9517-8b643e5ba9cb.png)

**Comment by Nighthawk22** [comment]
Sorry did not see that bower is not supported anymore.

**Comment by Greenek** [comment]
If you still need it: https://github.com/esvit/ng-table/issues/948#issuecomment-268831461
