### ISSUE TITLE
Sorting arrows disappear after concatenation to vendor.js

### ISSUE THREAD

**Issue by pbouda** [esvit/ng-table#931]
I have a strange problem that the sorting arrows of my table disappear when I uglify my app's code. I have no idea if this is a problem of ng-table or the rest of my app and am a bit lost... Maybe anybody has an idea where I can look for the source of the problem. I use several Angular plugins in my app but ng-table is the only one where I can see a problem, and it's only that the sorting arrows disappear (search works, pagination works). I used version 1.0.0 before, right now I tried with the current master and I have the problem in both cases.

**Comment by pbouda** [comment]
Update: Actually, it is not the uglification that causes the problem, but concatenation of the JS files (I have a "vendor.js" with Angular and all plugins). Even if I pull out ng-table and put it in a different file (so I have a "vendor.js" without ng-table and a "ng-table.js") it does not work. It's still just the sorting that's not working. I am clueless.

**Comment by elfouad** [comment]
I have the same problem. Do you have found a solution ?

**Comment by pbouda** [comment]
Uff, yeah, just found it. It's actually not the concatenation but the htmlmin. There is an issue allready, #230.
