### ISSUE TITLE
Support ng-hide

### ISSUE THREAD

**Issue by elnur** [esvit/ng-table#94]
It's possible to show columns conditionally using `ng-show` now, but `ng-hide` won't hide the header column. Please add support for that directive as well.

**Comment by zdila** [comment]
It works with this:
```html
...
<table ng-table="tableParams" ...
  ...
  <td ng-show="tableParams.myShowFlag">
  ...
```

```javascript
...
getData: function ($defer, params) {
  params.myShowFlag = false;
  ...
}
...
```

**Comment by TeodorKolev** [comment]
@zdila Any ng-if example?

**Comment by christianacca** [comment]
So I'm going to be reviewing the use of ng-show vs ng-if as a way of
showing/hiding columns in ng-table.

I suspect there are some reasonable perf improvements when using ng-if for
wide tables. If so I'm going to swap any internal use of ng-show to using
ng-if. Just need to be tread carefully to ensure that the public api is as
far as possible backwards compatible.

**Comment by TeodorKolev** [comment]
So many wasted words

**Comment by christianacca** [comment]
Crap you're right. Didn't see the previous conversation for this issue -
lack of sleep taking its toll

**Comment by christianacca** [comment]
FYI, ng-show has been replaced with `ng-if`. For details see https://github.com/esvit/ng-table/commit/b226dec9537769aaf355bf5a908f380622feba92
