### ISSUE TITLE
Unable to make NgTable work with AngularJs 1.5

### ISSUE THREAD

**Issue by mpetrucc** [esvit/ng-table#966]
Hello, i'm trying to integrate NgTable with angularjs 1.5 in a component-based architecture (so, no old-style controllers).
The NgTable controls (filter, icons for sorting) appear, but they don't seem to work at all, so they don't filter and don't sort.
It seems a compatibility issue with AngularJs >=1.5. 

We tested:

- with AngularJs 1.5.8 + Ng-Table 3.0.1 and 'new' Components (here is a [plnkr](http://plnkr.co/edit/q7c9qDruAGPaAxvhuAvh) ) 

- with AngularJs 1.6.1 + Ng-Table 2.0.1 and 'old style' Controller (sample from [jsbin](http://jsbin.com/kufuvoh/edit?html,js,output) )

Please help me

**Comment by christianacca** [comment]
I'll have a look the next couple of days.

In the meantime, have a look at this working codepen:
http://codepen.io/christianacca/pen/VLROaW

It's using angular 1.5.10 and it is working with the old style
controller's. Maybe compare it with what you have that's not working and
see if there is any notable difference.

C

**Comment by mpetrucc** [comment]
Thanks, I could have a look and maybe I've found the point. 
The issue in the case of the "old Style" controller is due to the html row
`<tr ng-repeat="user in vm.data">`

if I change it to 

`<tr ng-repeat="user in $data">`

as in your sample, everything works. And also in the 'new Style' controller.
It works also using 

`vm.tableParams.data`

on the ng-repeat for the controller example or 
 
`$ctrl.tableParams.data`

for the component, which let me fill much better than using $data.

Why don't you remove the "ugly" $data ?
