### ISSUE TITLE
ngtable pagination issue

### ISSUE THREAD

**Issue by 2103naveen** [esvit/ng-table#972]
I have created angular js ng table and changing the state on click of a row.

Issue: If i click on the row of second page(3rd or 4th etc ) of the ngtable, ngtable is again showing the first page.

Please let the fix for this.

My js file.

$scope.tableParams = new NgTableParams({count: 5, sorting: {name: 'asc'}
}, { counts:[5, 10, 15], dataset: $scope.tableData});

My HTML file.

<table ng-table="tableParams" class="table table table-striped table-hover table-bordered lctable" show-filter="true">
    <tr ng-repeat="lcData in $data" ng-class="{'selected-row':$index == selectedRow}" ui-sref=".lcTabs({id: lcData.id})" ui-sref-opts="{reload: true}" >

**Comment by PhilippMeissner** [comment]
Maybe it'd be a little more helpful if you can provide a more in-depth code snippet. Like, what did you change the `onClick` event to? What's supposed to happen and what does instead happen?
