### ISSUE TITLE
Angular type def doesnt exist

### ISSUE THREAD

**Issue by avihaymenahem** [esvit/ng-table#973]
Running npm install with @types/angular returns error and cant install.

When seaeched for types/angular on github, ive seen it doesnt exist...

Any solution?
(--only=dev doesnt work also)

**Comment by ccrowhurstram** [comment]
The type declaration files are included in the ng-table npm package itself. This is the same as angular 2 - it does not have any external @types package(s)

**Comment by avihaymenahem** [comment]
@ccrowhurstram when im running npm install, it fails becuase of the following:
"dependencies": {
    "@types/angular": "^1.5.13"
  }

So if it doesnt need it, why its on deps?

**Comment by ccrowhurstram** [comment]
Ah, OK I see. 

Sorry I had it my head that you were talking about wanting to install type declarations for the ng-table code itself.

@types/angular is a package over on the npm registry. This is maintained by the angular team.

I can see that it is available on the npm registry by running the following cmd: `npm info @types/angular versions --json`

So can't really help why it's not installing on your machine...

**Comment by avihaymenahem** [comment]
i tried it from 6 different servers in 6 different locations (amsterdam, israel, usa, china, moscow, australia), and none of them seems to recognize that... weird

**Comment by ccrowhurstram** [comment]
did you try running the cmd I used to list the versions of @types/angular on npm? 

I see the following:

![image](https://cloud.githubusercontent.com/assets/8319020/23168851/8e159d6a-f841-11e6-94ef-62016204a720.png)

**Comment by avihaymenahem** [comment]
The Error:

![1](https://cloud.githubusercontent.com/assets/1249445/23168846/4fac0152-f852-11e6-9314-60d0a65f8c08.png)

**Comment by avihaymenahem** [comment]
@ccrowhurstram Versions returns error on one server, and null response on the other

**Comment by ccrowhurstram** [comment]
Looks like it's a problem with your environment... maybe permissions related

**Comment by avihaymenahem** [comment]
New envs, new machines, on local, aws, softlayer and vultr.
Brand new , with no changes than default.
Weird...

**Comment by ccrowhurstram** [comment]
computers... can't live with them, can't live without

**Comment by avihaymenahem** [comment]
Seems like when working with private repos (Nexus, etc) you need to explicitly set the registry to npm's one (Even when proxy is on to the original) :)

@ccrowhurstram Thanks!!
