### ISSUE TITLE
how can I get dist files after bower install

### ISSUE THREAD

**Issue by jinryung1983** [esvit/ng-table#980]
How are you.
I tried to use ng-table in my project(angular 1.x).
so, I'd written as "ng-table": "latest" in bower.json file.
after "bower install", I can see "ng-table" directory in bower_components directory.
however, I can't see any dist files and folder.
What is my issue.
Help me~~

**Comment by nielskramerr** [comment]
@jinryung1983 Look in the readme of the project.

> Bower: NO LONGER SUPPORTED

**Comment by Greenek** [comment]
@jinryung1983: you can use my fork. Available [here](https://github.com/Greenek/bower-ng-table).

`bower install ng-table-bundle#latest --save`
