### ISSUE TITLE
`TypeError: NgTableParams is not a constructor` 

### ISSUE THREAD

**Issue by innatewonderer** [esvit/ng-table#983]
I have Angular 1.6.3 app with ng-table version 3.0.1
I load ng-table
```
(() => {
  angular.module('myApp', ['ngTable'])
})()
```
And then use it in one of my components:
```
(() => {
  let mainComponent = {
    controller: componentController,
    templateUrl: "views/models/component.html"
  }

  mainComponent.$inject = ['NgTableParams']

  function componentController(NgTableParams) {
    vm.tableParams = new NgTableParams({}, {
      dataset: data
    })
  }
})()
```

However, I still get `TypeError: NgTableParams is not a constructor` when trying to load the app.
When I added a break point, `NgTableParams` came up `undefined`. Suggestions?

**Comment by murilosdv** [comment]
Did you managed to fix it?

**Comment by innatewonderer** [comment]
Yes, I have.

It turned out that if you are loading `$scope` or `$state` object into the same controller, you must `$inject`it as well and in the same order.

```
mainComponent.$inject = ['$state', 'NgTableParams']

  function componentController($state, NgTableParams) {
```
