### ISSUE TITLE
Website down

### ISSUE THREAD

**Issue by victorbadila** [esvit/ng-table#997]
I know it's not a real code issue, but the website that supports the documentation: http://ng-table.com/ is currently out: "Fastly error: unknown domain: ng-table.com. Please check that this domain has been added to a service."

It's pretty frustrating as I almost finished most of an app using this and I have to finish it and present it soon :)

**Comment by christianacca** [comment]
Thanks for reporting the problem. I'll contact the owner of the site and
let him know.

C

**Comment by victorbadila** [comment]
website is up again, thanks!
